/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Teacher_Frames;

import Admin_Frames.Admin_Options_CoursesAndModules;
import Reports_Frames.FullStudentReport;
import Reports_Frames.Reports_Distinction_Students_by_Module;
import Reports_Frames.Reports_Full_Class_Group;
import Reports_Frames.Reports_Module_by_AllGroups;
import Reports_Frames.Reports_ModuleByClass;
import Login_Frames.Login_Frame;


/**
 *
 * @author cjunior
 */
public class Teacher_Options extends javax.swing.JFrame {

    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Teacher_Options.class.getName());

    /**
     * Creates new form LoginFrame
     */
    public Teacher_Options() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jButtonBackToLogin = new javax.swing.JButton();
        jButtonExit = new javax.swing.JButton();
        jButtonEnterResultsByStudent = new javax.swing.JButton();
        jButtonEnterResultsByClass = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButtonFullStudentRecord = new javax.swing.JButton();
        jButtonModuleResultsByClass = new javax.swing.JButton();
        jButtonModuleResultsAllGroups = new javax.swing.JButton();
        jButtonModuleResultsDistinction = new javax.swing.JButton();
        jButtonModuleResultsFullClass = new javax.swing.JButton();
        jButtonCoursesAndModules = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jButtonBackToLogin.setText("Logout");
        jButtonBackToLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackToLoginActionPerformed(evt);
            }
        });

        jButtonExit.setText("Exit");
        jButtonExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExitActionPerformed(evt);
            }
        });

        jButtonEnterResultsByStudent.setText("by Students");
        jButtonEnterResultsByStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEnterResultsByStudentActionPerformed(evt);
            }
        });

        jButtonEnterResultsByClass.setText("by Class");
        jButtonEnterResultsByClass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEnterResultsByClassActionPerformed(evt);
            }
        });

        jLabel1.setText("Enter / Update Results");

        jLabel2.setText("View Reports:");

        jButtonFullStudentRecord.setText("Full Student Record ");
        jButtonFullStudentRecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFullStudentRecordActionPerformed(evt);
            }
        });

        jButtonModuleResultsByClass.setText("Module Results (by Class Group)");
        jButtonModuleResultsByClass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModuleResultsByClassActionPerformed(evt);
            }
        });

        jButtonModuleResultsAllGroups.setText("Module Results (All Groups)");
        jButtonModuleResultsAllGroups.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModuleResultsAllGroupsActionPerformed(evt);
            }
        });

        jButtonModuleResultsDistinction.setText("Distinction Students by Module");
        jButtonModuleResultsDistinction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModuleResultsDistinctionActionPerformed(evt);
            }
        });

        jButtonModuleResultsFullClass.setText("Full Class Group Report");
        jButtonModuleResultsFullClass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModuleResultsFullClassActionPerformed(evt);
            }
        });

        jButtonCoursesAndModules.setText("Courses and Modules");
        jButtonCoursesAndModules.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCoursesAndModulesActionPerformed(evt);
            }
        });

        jLabel3.setText("View Course details");

        jLabel4.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel4.setText("Logged in as Teacher");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButtonEnterResultsByStudent, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButtonEnterResultsByClass, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButtonCoursesAndModules, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(70, 70, 70))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(58, 58, 58)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(39, 39, 39)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jButtonFullStudentRecord, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jButtonModuleResultsByClass, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jButtonModuleResultsAllGroups, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jButtonModuleResultsDistinction, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jButtonModuleResultsFullClass, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel2)
                                        .addGap(90, 90, 90))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonBackToLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonExit, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(jLabel4)))
                .addGap(63, 63, 63))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel4)
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonFullStudentRecord, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonModuleResultsByClass, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonEnterResultsByStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonEnterResultsByClass, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonModuleResultsAllGroups, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonModuleResultsDistinction, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonCoursesAndModules, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonModuleResultsFullClass, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonExit, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonBackToLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExitActionPerformed
    this.dispose();       
    }//GEN-LAST:event_jButtonExitActionPerformed

    private void jButtonBackToLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackToLoginActionPerformed
    Login_Frame f = new Login_Frame();
    f.setVisible(true);
    this.dispose();
    }//GEN-LAST:event_jButtonBackToLoginActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
     
    }//GEN-LAST:event_formWindowActivated

    private void jButtonEnterResultsByStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEnterResultsByStudentActionPerformed
    Teacher_EnterResultsByStudent f = new Teacher_EnterResultsByStudent();
    f.setVisible(true);
    this.dispose();
    }//GEN-LAST:event_jButtonEnterResultsByStudentActionPerformed

    private void jButtonEnterResultsByClassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEnterResultsByClassActionPerformed
    Teacher_EnterResultsByClass f = new Teacher_EnterResultsByClass();
    f.setVisible(true);
    this.dispose();
    }//GEN-LAST:event_jButtonEnterResultsByClassActionPerformed

    private void jButtonFullStudentRecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFullStudentRecordActionPerformed
    FullStudentReport f = new FullStudentReport();
    f.setVisible(true);
    this.dispose();
    }//GEN-LAST:event_jButtonFullStudentRecordActionPerformed

    private void jButtonModuleResultsByClassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModuleResultsByClassActionPerformed
    Reports_ModuleByClass f = new Reports_ModuleByClass();
    f.setVisible(true);
    this.dispose();
    }//GEN-LAST:event_jButtonModuleResultsByClassActionPerformed

    private void jButtonModuleResultsAllGroupsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModuleResultsAllGroupsActionPerformed
    Reports_Module_by_AllGroups f = new Reports_Module_by_AllGroups();
    f.setVisible(true);
    this.dispose();
    }//GEN-LAST:event_jButtonModuleResultsAllGroupsActionPerformed

    private void jButtonModuleResultsDistinctionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModuleResultsDistinctionActionPerformed
    Reports_Distinction_Students_by_Module f = new Reports_Distinction_Students_by_Module();
    f.setVisible(true);
    this.dispose();
    }//GEN-LAST:event_jButtonModuleResultsDistinctionActionPerformed

    private void jButtonModuleResultsFullClassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModuleResultsFullClassActionPerformed
    Reports_Full_Class_Group f = new Reports_Full_Class_Group();
    f.setVisible(true);
    this.dispose();
    }//GEN-LAST:event_jButtonModuleResultsFullClassActionPerformed

    private void jButtonCoursesAndModulesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCoursesAndModulesActionPerformed
        Admin_Options_CoursesAndModules f = new Admin_Options_CoursesAndModules();
        f.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonCoursesAndModulesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Teacher_Options().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBackToLogin;
    private javax.swing.JButton jButtonCoursesAndModules;
    private javax.swing.JButton jButtonEnterResultsByClass;
    private javax.swing.JButton jButtonEnterResultsByStudent;
    private javax.swing.JButton jButtonExit;
    private javax.swing.JButton jButtonFullStudentRecord;
    private javax.swing.JButton jButtonModuleResultsAllGroups;
    private javax.swing.JButton jButtonModuleResultsByClass;
    private javax.swing.JButton jButtonModuleResultsDistinction;
    private javax.swing.JButton jButtonModuleResultsFullClass;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    // End of variables declaration//GEN-END:variables
}
