/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Teacher_Frames;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.time.LocalDate;
import javax.swing.JOptionPane;
import my.fp.Classes.Student;

/**
 *
 * @author cjunior
 */
public class Teacher_EnterResultsByStudent extends javax.swing.JFrame {

    private static final String URL = "jdbc:mysql://localhost:3306/final_project";
    private static final String USER = "root";      // seu usuário MySQL
    private static final String PASSWORD = "Root@1234"; // sua senha
    private int selectedStudentId;
    private String moduleName;
    private double A1;
    private double A2;
    private double exam;

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Teacher_EnterResultsByStudent.class.getName());

    /**
     * Creates new form StaffFrame
     */
    public Teacher_EnterResultsByStudent() {

        initComponents();
    }

    public Teacher_EnterResultsByStudent(int selectedStudentId) {
        initComponents();
        this.selectedStudentId = selectedStudentId;

        loadStudentResults();
    }

    private void loadStudentResults() {
        // aqui você usa selectedStudentId para buscar no banco
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonBackToOptions = new javax.swing.JButton();
        jButtonExit = new javax.swing.JButton();
        jButtonPrint = new javax.swing.JButton();
        jLabelStudentName1 = new javax.swing.JLabel();
        jButtonClean = new javax.swing.JButton();
        jComboBoxSelectStudent = new javax.swing.JComboBox<>();
        jButtonSearch = new javax.swing.JButton();
        jLabelStudentName3 = new javax.swing.JLabel();
        jButtonEnterResults = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableResults = new javax.swing.JTable();
        jLabelStudentName = new javax.swing.JLabel();
        jLabelCourse = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jButtonBackToOptions.setText("Back");
        jButtonBackToOptions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackToOptionsActionPerformed(evt);
            }
        });

        jButtonExit.setText("Exit");
        jButtonExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExitActionPerformed(evt);
            }
        });

        jButtonPrint.setText("Print results");
        jButtonPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPrintActionPerformed(evt);
            }
        });

        jLabelStudentName1.setText("Select student:");

        jButtonClean.setText("Clean Search");
        jButtonClean.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCleanActionPerformed(evt);
            }
        });

        jButtonSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Images/Search_icon.png"))); // NOI18N
        jButtonSearch.setText("Search");
        jButtonSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSearchActionPerformed(evt);
            }
        });

        jLabelStudentName3.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabelStudentName3.setText("Enter Results by Student");

        jButtonEnterResults.setText("Save");
        jButtonEnterResults.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEnterResultsActionPerformed(evt);
            }
        });

        jTableResults.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Module", "Assignment 1", "Assignment 2", "Exam", "Result"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, true, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableResults);
        if (jTableResults.getColumnModel().getColumnCount() > 0) {
            jTableResults.getColumnModel().getColumn(0).setPreferredWidth(210);
            jTableResults.getColumnModel().getColumn(1).setPreferredWidth(100);
            jTableResults.getColumnModel().getColumn(2).setPreferredWidth(100);
            jTableResults.getColumnModel().getColumn(3).setPreferredWidth(100);
            jTableResults.getColumnModel().getColumn(4).setPreferredWidth(100);
        }

        jLabelStudentName.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabelStudentName.setText("Student name:");
        jLabelStudentName.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jLabelCourse.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabelCourse.setText("Course:");
        jLabelCourse.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelStudentName3)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelStudentName1, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBoxSelectStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonSearch))
                    .addComponent(jLabelCourse, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 682, Short.MAX_VALUE)
                    .addComponent(jLabelStudentName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(56, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(jButtonBackToOptions, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonClean, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19)
                        .addComponent(jButtonExit, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButtonEnterResults, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonPrint, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabelStudentName3)
                .addGap(18, 18, 18)
                .addComponent(jLabelStudentName1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jComboBoxSelectStudent)
                    .addComponent(jButtonSearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(40, 40, 40)
                .addComponent(jLabelStudentName, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelCourse)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
                .addGap(24, 24, 24)
                .addComponent(jButtonEnterResults, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonPrint, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonBackToOptions, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonExit, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonClean, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExitActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonExitActionPerformed

    private void jButtonBackToOptionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackToOptionsActionPerformed
        Teacher_Options f = new Teacher_Options();
        f.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonBackToOptionsActionPerformed

    private void jButtonPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPrintActionPerformed
        printToPDF();
    }//GEN-LAST:event_jButtonPrintActionPerformed

    private void jButtonCleanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCleanActionPerformed
        cleanFields();
    }//GEN-LAST:event_jButtonCleanActionPerformed

    private void jButtonSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSearchActionPerformed
        // Get the table model and clear existing rows
        var model = (javax.swing.table.DefaultTableModel) jTableResults.getModel();
        model.setRowCount(0);

        // Get the selected object from the ComboBox
        Object selectedItem = jComboBoxSelectStudent.getSelectedItem();

        // Validation: Check if something is selected and if it's an instance of Student class
        if (selectedItem == null || !(selectedItem instanceof Student)) {
            JOptionPane.showMessageDialog(this, "Please select a valid student from the list.");
            return;
        }

        // Cast the selected item to Student object to access its methods
        Student selectedStudent = (Student) selectedItem;
        int studentId = selectedStudent.getStudentId();
        this.selectedStudentId = studentId; // Update global variable

       // Prepare SQL Query
        String sql = """
        SELECT 
        s.first_name,
        s.middle_name,
        s.surname, 
        c.course_name, 
        m.module_name, 
        a.assignment_1, 
        a.assignment_2, 
        a.exam, 
        a.result
        FROM student s
        JOIN class_group cg        ON s.class_group_code = cg.class_group_code
        JOIN course c             ON cg.course_id = c.course_id
        JOIN course_has_module chm ON c.course_id = chm.course_id 
        JOIN module m             ON chm.qqi_module_code = m.qqi_module_code
        LEFT JOIN assessment a    ON (
        a.student_id = s.student_id AND 
        a.qqi_module_code = m.qqi_module_code
        )
        WHERE s.student_id = ?
        ORDER BY m.module_name ASC;
        """;

        // Establish database connection and execute prepared statement
        try (Connection con = DriverManager.getConnection(URL, USER, PASSWORD); PreparedStatement ps = con.prepareStatement(sql)) {

            ps.setInt(1, studentId);

            try (ResultSet rs = ps.executeQuery()) {
                boolean dataFound = false;

                while (rs.next()) {
                    // Update UI labels only once using data from the first row
                    if (!dataFound) {
                        String fullName = rs.getString("first_name") + " " + rs.getString("middle_name") + " " + rs.getString("surname");
                        jLabelStudentName.setText("Student: " + fullName);
                        jLabelCourse.setText("Course: " + rs.getString("course_name"));
                        dataFound = true;
                    }

                    // Retrieve module and grades (handling potential nulls from LEFT JOIN)
                    String sqlmoduleName = rs.getString("module_name");
                    Object sqla1 = rs.getObject("assignment_1");
                    Object sqla2 = rs.getObject("assignment_2");
                    Object sqlexam = rs.getObject("exam");
                    Object sqlresult = rs.getObject("result");

                    // Add formatted row to the JTable
                    model.addRow(new Object[]{
                        sqlmoduleName,
                        sqla1,
                        sqla2,
                        sqlexam,
                        sqlresult
                    });
                }

                // Inform user if no records were returned for the specific ID
                if (!dataFound) {
                    JOptionPane.showMessageDialog(this, "No records found for the selected student.");
                }
            }
        } catch (SQLException e) {
            // Log and display database-related errors
            JOptionPane.showMessageDialog(this, "Database error: " + e.getMessage());
            logger.log(java.util.logging.Level.SEVERE, "Database error occurred", e);
        }
    }//GEN-LAST:event_jButtonSearchActionPerformed

    private void jButtonEnterResultsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEnterResultsActionPerformed
        // Force the table to stop editing to capture the last typed value
        if (jTableResults.isEditing()) {
            jTableResults.getCellEditor().stopCellEditing();
        }

        // Security check: make sure a student was loaded
        if (selectedStudentId == 0) {
            JOptionPane.showMessageDialog(this, "Please select a student and search first.");
            return;
        }

        // RUN VALIDATION
        if (!validateGrades()) {
            return;
        }

        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) jTableResults.getModel();
        int rowCount = model.getRowCount();

        // Simplified SQL using the hidden ID
        String sqlUpdate = """
        UPDATE assessment a 
        JOIN module m ON a.qqi_module_code = m.qqi_module_code
        SET a.assignment_1 = ?, a.assignment_2 = ?, a.exam = ?, a.result = ?
        WHERE a.student_id = ? AND m.module_name = ?
        """;

        try (Connection con = DriverManager.getConnection(URL, USER, PASSWORD); PreparedStatement ps = con.prepareStatement(sqlUpdate)) {

            for (int i = 0; i < rowCount; i++) {
                moduleName = model.getValueAt(i, 0).toString();

                // Grades already validated by validateGrades
                A1 = Double.parseDouble(model.getValueAt(i, 1).toString());
                A2 = Double.parseDouble(model.getValueAt(i, 2).toString());
                exam = Double.parseDouble(model.getValueAt(i, 3).toString());

                double result = Math.round(((A1 + A2 + exam) / 3.0) * 100.0) / 100.0;

                // Confirm save for each row (or you can move this outside the loop for a single confirmation)
                String message = "Save grades for: " + moduleName + "?\n\n"
                        + "Assignment 1: " + A1 + "\n"
                        + "Assignment 2: " + A2 + "\n"
                        + "Exam: " + exam + "\n\n"
                        + "FINAL RESULT: " + String.format("%.2f", result);

                int choice = JOptionPane.showConfirmDialog(null,
                        message,
                        "Confirm Save",
                        JOptionPane.YES_NO_CANCEL_OPTION);

                if (choice == JOptionPane.YES_OPTION) {
                    ps.setDouble(1, A1);
                    ps.setDouble(2, A2);
                    ps.setDouble(3, exam);
                    ps.setDouble(4, result);
                    ps.setInt(5, selectedStudentId);
                    ps.setString(6, moduleName);

                    ps.executeUpdate();
                } else if (choice == JOptionPane.CANCEL_OPTION) {
                    // Stop the process for the rest of the class
                    break;
                }
            }
            JOptionPane.showMessageDialog(this, "Process finished.");

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Database error: " + e.getMessage());
            logger.log(java.util.logging.Level.SEVERE, "Database error occurred", e);
        }

        UpdateSearch(); // Refresh the table with new results


    }//GEN-LAST:event_jButtonEnterResultsActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

        String sql = "SELECT student_id, first_name, middle_name, surname FROM student ORDER BY first_name, surname";

        try (Connection con = DriverManager.getConnection(URL, USER, PASSWORD); PreparedStatement ps = con.prepareStatement(sql); ResultSet res = ps.executeQuery()) {

            jComboBoxSelectStudent.removeAllItems();

            while (res.next()) {
                int id = res.getInt("student_id");
                String first = res.getString("first_name");
                String middle = res.getString("middle_name");
                String last = res.getString("surname");

                String fullName = (first != null ? first : "") + " "
                        + (middle != null ? middle : "") + " "
                        + (last != null ? last : "");

                //Clean spaces
                fullName = fullName.trim().replaceAll("\\s+", " ");

                //Create a new Student (Class) with student_id,and names, add at Combo Box
                jComboBoxSelectStudent.addItem(new Student(id, fullName, ""));
            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Erro: " + e.getMessage());
        }
        jComboBoxSelectStudent.setSelectedIndex(-1);
    }//GEN-LAST:event_formWindowOpened

    private void UpdateSearch() {

        var model = (javax.swing.table.DefaultTableModel) jTableResults.getModel();
        model.setRowCount(0);

        String sql = """
        SELECT 
            s.first_name, 
            s.surname, 
            c.course_name, 
            m.module_name, 
            a.assignment_1, 
            a.assignment_2, 
            a.exam, 
            a.result
        FROM student s
        JOIN class_group cg        ON s.class_group_code = cg.class_group_code
        JOIN course c             ON cg.course_id = c.course_id
        -- Ajustado para o nome exato da coluna na tabela associativa:
        JOIN course_has_module chm ON c.course_id = chm.course_id 
        JOIN module m             ON chm.qqi_module_code = m.qqi_module_code
        LEFT JOIN assessment a    ON (
            a.student_id = s.student_id AND 
            a.qqi_module_code = m.qqi_module_code
        )
        WHERE s.student_id = ?
        ORDER BY m.module_name ASC, s.student_id ASC;
    """;

        try (Connection con = DriverManager.getConnection(URL, USER, PASSWORD); PreparedStatement ps = con.prepareStatement(sql)) {

            ps.setInt(1, selectedStudentId);

            try (ResultSet rs = ps.executeQuery()) {
                boolean studentFound = false;

                while (rs.next()) {
                    // 1. Captura o nome e curso apenas na primeira linha encontrada
                    if (!studentFound) {
                        String fullName = rs.getString("first_name") + " " + rs.getString("surname");
                        jLabelStudentName.setText("Student: " + fullName);
                        jLabelCourse.setText("Course: " + (rs.getString("course_name")));

                        studentFound = true;
                    }

                    String moduleName = rs.getString("module_name");
                    if (moduleName == null) {
                        continue;
                    }

                    // 2. Captura as notas
                    Object a1 = rs.getObject("assignment_1");
                    Object a2 = rs.getObject("assignment_2");
                    Object exam = rs.getObject("exam");
                    Object result = rs.getObject("result");

                    // 3. Adiciona a linha (Evite duplicados: se os campos de nota forem null, 
                    model.addRow(new Object[]{
                        moduleName,
                        a1,
                        a2,
                        exam,
                        result // O Swing renderiza null como célula vazia automaticamente
                    });
                }

            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Database error: " + e.getMessage());
        }

    }

    private void cleanFields() {

        //Clean Labels
        jLabelStudentName.setText("Student:");
        jLabelCourse.setText("Course:");

        // Clean the table
        var model = (javax.swing.table.DefaultTableModel) jTableResults.getModel();
        model.setRowCount(0);

        //Set ComboBoxSelection to "Empty"
        jComboBoxSelectStudent.setSelectedIndex(-1);

    }

    private void printToPDF() {
        // 1. basic validation
        if (jTableResults.getRowCount() == 0) {
            JOptionPane.showMessageDialog(this, "Search for a student and results first!");
            return;
        }

        // 2. " Save as" windows
        javax.swing.JFileChooser chooser = new javax.swing.JFileChooser();
        chooser.setDialogTitle("Save Report");
        int Year = LocalDate.now().getYear(); //This year
        chooser.setSelectedFile(new java.io.File("REPORT_ACADEMIC_RECORD_" + Year + "_" + jLabelStudentName.getText() + ".pdf"));

        if (chooser.showSaveDialog(this) == javax.swing.JFileChooser.APPROVE_OPTION) {
            String path = chooser.getSelectedFile().getAbsolutePath();
            if (!path.endsWith(".pdf")) {
                path += ".pdf";
            }

            try {
                com.itextpdf.text.Document document = new com.itextpdf.text.Document();
                com.itextpdf.text.pdf.PdfWriter.getInstance(document, new java.io.FileOutputStream(path));

                document.open();

                // Style and content
                document.add(new com.itextpdf.text.Paragraph("STUDENT ACADEMIC RECORD " + Year));
                document.add(new com.itextpdf.text.Paragraph(jLabelStudentName.getText()));
                document.add(new com.itextpdf.text.Paragraph(jLabelCourse.getText()));
                document.add(new com.itextpdf.text.Paragraph(" ")); // Space

                // New table nn PDF
                var model = (javax.swing.table.DefaultTableModel) jTableResults.getModel();
                com.itextpdf.text.pdf.PdfPTable pdfTable = new com.itextpdf.text.pdf.PdfPTable(model.getColumnCount());

                // Heads
                for (int i = 0; i < model.getColumnCount(); i++) {
                    pdfTable.addCell(model.getColumnName(i));
                }

                // Data
                for (int r = 0; r < model.getRowCount(); r++) {
                    for (int c = 0; c < model.getColumnCount(); c++) {
                        Object value = model.getValueAt(r, c);
                        pdfTable.addCell(value == null ? "-" : value.toString());
                    }
                }

                document.add(pdfTable);
                document.close();

                JOptionPane.showMessageDialog(this, "PDF saved successfully!");

            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Error generating PDF: " + e.getMessage());
            }
        }
    }
    
    private boolean validateGrades() {
    javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) jTableResults.getModel();
    int emptyFieldsCount = 0; // Counter for empty fields

    for (int i = 0; i < model.getRowCount(); i++) {
        Object modValue = model.getValueAt(i, 0);
        String modName = (modValue == null) ? "Unknown" : modValue.toString();

        for (int col = 1; col <= 3; col++) {
            Object value = model.getValueAt(i, col);
            String colName = jTableResults.getColumnName(col);
            double grade;

            // 1. Check for NULL or EMPTY fields
            if (value == null || value.toString().trim().isEmpty()) {
                grade = 0.0;
                model.setValueAt(grade, i, col); 
                emptyFieldsCount++; // Increment counter
            } else {
                try {
                    String rawValue = value.toString().trim().replace(",", ".");
                    grade = Double.parseDouble(rawValue);

                    if (grade < 0 || grade > 10) {
                        JOptionPane.showMessageDialog(this,
                                "Invalid grade in module: " + modName + "!\n"
                                + "Field: " + colName + "\n"
                                + "Value: " + grade + "\n"
                                + "Grades must be between 0.00 and 10.00.");
                        return false;
                    }
                    model.setValueAt(grade, i, col);
                } catch (NumberFormatException e) {
                    JOptionPane.showMessageDialog(this,
                            "Invalid format in module: " + modName + " (" + colName + ").\n"
                            + "Please enter only numbers or leave it blank for 0.00.");
                    return false;
                }
            }
        }
    }

    // 2. SHOW ALERT IF EMPTY FIELDS WERE FOUND
    if (emptyFieldsCount > 0) {
        int response = JOptionPane.showConfirmDialog(this,
                "Warning: " + emptyFieldsCount + " empty field(s) detected.\n"
                + "They have been automatically set to 0.00.\n"
                + "Do you want to proceed with these values?",
                "Empty Fields Detected",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.WARNING_MESSAGE);
        
        if (response == JOptionPane.NO_OPTION) {
            return false; // Stop the process so the teacher can edit
        }
    }

    return true;
}

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        java.awt.EventQueue.invokeLater(() -> new Teacher_EnterResultsByStudent().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBackToOptions;
    private javax.swing.JButton jButtonClean;
    private javax.swing.JButton jButtonEnterResults;
    private javax.swing.JButton jButtonExit;
    private javax.swing.JButton jButtonPrint;
    private javax.swing.JButton jButtonSearch;
    private javax.swing.JComboBox<Student> jComboBoxSelectStudent;
    private javax.swing.JLabel jLabelCourse;
    private javax.swing.JLabel jLabelStudentName;
    private javax.swing.JLabel jLabelStudentName1;
    private javax.swing.JLabel jLabelStudentName3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableResults;
    // End of variables declaration//GEN-END:variables
}
