/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Reports_Frames;

import Teacher_Frames.*;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author cjunior
 */
public class FullStudentReport extends javax.swing.JFrame {

    private static final String URL = "jdbc:mysql://localhost:3306/final_project";
    private static final String USER = "root";      // seu usuário MySQL
    private static final String PASSWORD = "Root@1234"; // sua senha
    private int selectedStudentId;

    /**
     * Creates new form StaffFrame
     */
    public FullStudentReport() {

        initComponents();
    }

    public FullStudentReport(int selectedStudentId) {
        initComponents();
        this.selectedStudentId = selectedStudentId;

        loadStudentResults();
    }

    private void loadStudentResults() {
        // aqui você usa selectedStudentId para buscar no banco
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonBackToOptions = new javax.swing.JButton();
        jButtonExit = new javax.swing.JButton();
        jButtonPrint = new javax.swing.JButton();
        jLabelStudentName1 = new javax.swing.JLabel();
        jButtonClean = new javax.swing.JButton();
        jComboBoxSelectStudent = new javax.swing.JComboBox<>();
        jButtonSearch = new javax.swing.JButton();
        jLabelStudentName3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableResults = new javax.swing.JTable();
        jLabelStudentName = new javax.swing.JLabel();
        jLabelCourse = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jButtonBackToOptions.setText("Back");
        jButtonBackToOptions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackToOptionsActionPerformed(evt);
            }
        });

        jButtonExit.setText("Exit");
        jButtonExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExitActionPerformed(evt);
            }
        });

        jButtonPrint.setText("Print results");
        jButtonPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPrintActionPerformed(evt);
            }
        });

        jLabelStudentName1.setText("Select student:");

        jButtonClean.setText("Clean Search");
        jButtonClean.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCleanActionPerformed(evt);
            }
        });

        jButtonSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Images/Search_icon.png"))); // NOI18N
        jButtonSearch.setText("Search");
        jButtonSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSearchActionPerformed(evt);
            }
        });

        jLabelStudentName3.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabelStudentName3.setText("Student Report");

        jTableResults.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Module", "Assignment 1", "Assignment 2", "Exam", "Result"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableResults);
        if (jTableResults.getColumnModel().getColumnCount() > 0) {
            jTableResults.getColumnModel().getColumn(0).setPreferredWidth(200);
            jTableResults.getColumnModel().getColumn(1).setPreferredWidth(100);
            jTableResults.getColumnModel().getColumn(2).setPreferredWidth(100);
            jTableResults.getColumnModel().getColumn(3).setPreferredWidth(100);
            jTableResults.getColumnModel().getColumn(4).setPreferredWidth(100);
        }

        jLabelStudentName.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabelStudentName.setText("Student name:");
        jLabelStudentName.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jLabelCourse.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabelCourse.setText("Course:");
        jLabelCourse.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabelStudentName, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabelStudentName3)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelStudentName1, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBoxSelectStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonSearch))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 682, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(56, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonClean, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(59, 59, 59))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jButtonBackToOptions, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonPrint, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonExit, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabelStudentName3)
                .addGap(18, 18, 18)
                .addComponent(jLabelStudentName1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxSelectStudent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addComponent(jLabelStudentName, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelCourse)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonPrint, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonClean, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonExit, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonBackToOptions, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        String sql = "SELECT student_id, first_name, surname FROM student ORDER BY first_name, middle_name";

        try (Connection con = DriverManager.getConnection(URL, USER, PASSWORD); PreparedStatement ps = con.prepareStatement(sql); ResultSet res = ps.executeQuery()) {

            while (res.next()) {
                int id = res.getInt("student_id");
                String first = res.getString("first_name");
                String surname = res.getString("surname");

                String name
                        = (first == null ? "" : first) + " "
                        + (surname == null ? "" : surname);

                name = name.trim().replaceAll("\\s+", " ");

                jComboBoxSelectStudent.addItem(id + ": " + name);
            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Erro: " + e.getMessage());
        }
        jComboBoxSelectStudent.setSelectedIndex(-1);
    }//GEN-LAST:event_formWindowActivated

    private void jButtonExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExitActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonExitActionPerformed

    private void jButtonBackToOptionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackToOptionsActionPerformed
        Teacher_Options f = new Teacher_Options();
        f.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonBackToOptionsActionPerformed

    private void jButtonPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPrintActionPerformed
        printToPDF();
    }//GEN-LAST:event_jButtonPrintActionPerformed

    private void jButtonCleanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCleanActionPerformed
        cleanFields();
    }//GEN-LAST:event_jButtonCleanActionPerformed

    private void jButtonSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSearchActionPerformed
        var model = (javax.swing.table.DefaultTableModel) jTableResults.getModel();
        model.setRowCount(0);
        Object studentSelected = jComboBoxSelectStudent.getSelectedItem();
        if (studentSelected == null) {
            JOptionPane.showMessageDialog(this, "Please select a student.");
            return;
        }

        String selectedText = studentSelected.toString().trim();
        int colonIdx = selectedText.indexOf(':');

        int studentId;
        try {
            studentId = Integer.parseInt(selectedText.substring(0, colonIdx).trim());
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Invalid student ID.");
            return;
        }
        selectedStudentId = studentId;
        jLabelStudentName.setText("");
        jLabelCourse.setText("");

        String sql = """
    SELECT 
    s.first_name, 
    s.surname, 
    c.course_name, 
    m.module_name, 
    a.assignment_1, 
    a.assignment_2, 
    a.exam, 
    a.result
    FROM student s
    LEFT JOIN class_group cg        ON s.class_group_code = cg.class_group_code
    LEFT JOIN course c             ON cg.course_id = c.course_id
    LEFT JOIN course_has_module chm ON c.course_id = chm.course_id 
    LEFT JOIN module m             ON chm.qqi_module_code = m.qqi_module_code
    LEFT JOIN assessment a    ON (
    a.student_id = s.student_id AND 
    a.qqi_module_code = m.qqi_module_code
    )
    WHERE s.student_id = ?
    ORDER BY m.module_name ASC;
    """;

        try (Connection con = DriverManager.getConnection(URL, USER, PASSWORD); PreparedStatement ps = con.prepareStatement(sql)) {

            ps.setInt(1, studentId);

            try (ResultSet rs = ps.executeQuery()) {
                boolean studentFound = false;

                while (rs.next()) {
                    // 1. Captura o nome e curso apenas na primeira linha encontrada
                    if (!studentFound) {
                        String fullName = rs.getString("first_name") + " " + rs.getString("surname");
                        jLabelStudentName.setText("Student: " + fullName);
                        jLabelCourse.setText("Course: " + (rs.getString("course_name")));

                        studentFound = true;
                    }

                    String moduleName = rs.getString("module_name");
                    if (moduleName == null) {
                        continue;
                    }

                    // 2. Captura as notas
                    Object a1 = rs.getObject("assignment_1");
                    Object a2 = rs.getObject("assignment_2");
                    Object exam = rs.getObject("exam");
                    Object result = rs.getObject("result");

                    // 3. Adiciona a linha (Evite duplicados: se os campos de nota forem null, 
                    model.addRow(new Object[]{
                        moduleName,
                        a1, // Passa o objeto do banco direto (Integer ou null)
                        a2,
                        exam,
                        result // O Swing renderiza null como célula vazia automaticamente
                    });
                }

                if (!studentFound) {
                    JOptionPane.showMessageDialog(this, "Student not found (ID: " + studentId + ").");
                    return;
                }
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Database error: " + e.getMessage());
        }


    }//GEN-LAST:event_jButtonSearchActionPerformed

    private void cleanFields() {

        //Clean Labels
        jLabelStudentName.setText("Student:");
        jLabelCourse.setText("Course:");

        // Clean the table
        var model = (javax.swing.table.DefaultTableModel) jTableResults.getModel();
        model.setRowCount(0);

        //Set ComboBoxSelection to "Empty"
        jComboBoxSelectStudent.setSelectedIndex(-1);

    }

    private void printToPDF() {
        // 1. Validation: check if the table has data
        if (jTableResults.getRowCount() == 0) {
            JOptionPane.showMessageDialog(this, "Please search for a student and their results first!");
            return;
        }

        // 2. "Save as" dialog setup
        javax.swing.JFileChooser chooser = new javax.swing.JFileChooser();
        chooser.setDialogTitle("Save Student Report");

        int currentYear = java.time.LocalDate.now().getYear();

        // Using the student name from the label to name the file
        // Assuming jLabelStudentName has the text "Student: John Doe"
        String studentName = jLabelStudentName.getText().replace("Student: ", "").trim();
        String fileName = "ACADEMIC_RECORD_" + studentName.replace(" ", "_") + "_" + currentYear + ".pdf";

        chooser.setSelectedFile(new java.io.File(fileName));

        if (chooser.showSaveDialog(this) == javax.swing.JFileChooser.APPROVE_OPTION) {
            String path = chooser.getSelectedFile().getAbsolutePath();
            if (!path.endsWith(".pdf")) {
                path += ".pdf";
            }

            try {
                // 3. Document initialization with iText
                com.itextpdf.text.Document document = new com.itextpdf.text.Document();
                com.itextpdf.text.pdf.PdfWriter.getInstance(document, new java.io.FileOutputStream(path));

                document.open();

                // 4. Custom Fonts for Professional Look
                com.itextpdf.text.Font titleFont = new com.itextpdf.text.Font(com.itextpdf.text.Font.FontFamily.HELVETICA, 18, com.itextpdf.text.Font.BOLD);
                com.itextpdf.text.Font headerFont = new com.itextpdf.text.Font(com.itextpdf.text.Font.FontFamily.HELVETICA, 11, com.itextpdf.text.Font.BOLD);
                com.itextpdf.text.Font normalFont = new com.itextpdf.text.Font(com.itextpdf.text.Font.FontFamily.HELVETICA, 10, com.itextpdf.text.Font.NORMAL);

                // 5. Header Section
                document.add(new com.itextpdf.text.Paragraph("INDIVIDUAL ACADEMIC RECORD - " + currentYear, titleFont));
                document.add(new com.itextpdf.text.Paragraph("Student Name: " + studentName, normalFont));
                document.add(new com.itextpdf.text.Paragraph(jLabelCourse.getText(), normalFont)); // e.g., "Course: Computing"
                document.add(new com.itextpdf.text.Paragraph("Date of Issue: " + java.time.LocalDate.now(), normalFont));
                document.add(new com.itextpdf.text.Paragraph(" ")); // Spacer

                // 6. Table Setup (Matches the Module report style)
                javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) jTableResults.getModel();
                com.itextpdf.text.pdf.PdfPTable pdfTable = new com.itextpdf.text.pdf.PdfPTable(model.getColumnCount());
                pdfTable.setWidthPercentage(100);

                // Set relative widths (First column 'Module' wider than grade columns)
                float[] columnWidths = {4f, 2f, 2f, 2f, 2f};
                pdfTable.setWidths(columnWidths);

                // Adding Styled Table Headers
                for (int i = 0; i < model.getColumnCount(); i++) {
                    com.itextpdf.text.pdf.PdfPCell headerCell = new com.itextpdf.text.pdf.PdfPCell(new com.itextpdf.text.Phrase(model.getColumnName(i), headerFont));
                    headerCell.setBackgroundColor(com.itextpdf.text.BaseColor.LIGHT_GRAY);
                    headerCell.setHorizontalAlignment(com.itextpdf.text.Element.ALIGN_CENTER);
                    headerCell.setPadding(6);
                    pdfTable.addCell(headerCell);
                }

                // Adding Student Data
                for (int r = 0; r < model.getRowCount(); r++) {
                    for (int c = 0; c < model.getColumnCount(); c++) {
                        Object value = model.getValueAt(r, c);
                        com.itextpdf.text.pdf.PdfPCell dataCell = new com.itextpdf.text.pdf.PdfPCell(new com.itextpdf.text.Phrase(value == null ? "-" : value.toString(), normalFont));
                        dataCell.setPadding(4);
                        // Center align grade columns (index 1 to 4)
                        if (c > 0) {
                            dataCell.setHorizontalAlignment(com.itextpdf.text.Element.ALIGN_CENTER);
                        }
                        pdfTable.addCell(dataCell);
                    }
                }

                document.add(pdfTable);

                // 7. Footer / Signature Line
                document.add(new com.itextpdf.text.Paragraph(" "));
                document.add(new com.itextpdf.text.Paragraph("__________________________________", normalFont));
                document.add(new com.itextpdf.text.Paragraph("Academic Department Signature", normalFont));

                document.close();
                JOptionPane.showMessageDialog(this, "Student PDF Report saved successfully!");

            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Error generating PDF: " + e.getMessage());
            }
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        java.awt.EventQueue.invokeLater(() -> new FullStudentReport().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBackToOptions;
    private javax.swing.JButton jButtonClean;
    private javax.swing.JButton jButtonExit;
    private javax.swing.JButton jButtonPrint;
    private javax.swing.JButton jButtonSearch;
    private javax.swing.JComboBox<String> jComboBoxSelectStudent;
    private javax.swing.JLabel jLabelCourse;
    private javax.swing.JLabel jLabelStudentName;
    private javax.swing.JLabel jLabelStudentName1;
    private javax.swing.JLabel jLabelStudentName3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableResults;
    // End of variables declaration//GEN-END:variables
}
