/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Reports_Frames;

import Teacher_Frames.*;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

import Admin_Frames.Admin_Options;
import java.time.LocalDate;
import my.fp.Classes.DataStore;

/**
 *
 * @author cjunior
 */
public class Reports_ModuleByClass extends javax.swing.JFrame {

    private static final String URL = "jdbc:mysql://localhost:3306/final_project";
    private static final String USER = "root";      // seu usuário MySQL
    private static final String PASSWORD = "Root@1234"; // sua senha
    private static int selectedCourseID;
    private static int selectedClassID;
    private static String selectedModule;

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Reports_ModuleByClass.class.getName());

    /**
     * Creates new form StudentFrame
     */
    public Reports_ModuleByClass() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonExit = new javax.swing.JButton();
        jButtonBackToAdmin_Options = new javax.swing.JButton();
        jButtonClean = new javax.swing.JButton();
        jComboBoxCourse = new javax.swing.JComboBox<>();
        jButtonSearchCourse = new javax.swing.JButton();
        jLabelStudentName2 = new javax.swing.JLabel();
        jLabelStudentName3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableResults = new javax.swing.JTable();
        jLabelStudentName4 = new javax.swing.JLabel();
        jComboBoxClass = new javax.swing.JComboBox<>();
        jButtonSearchClass = new javax.swing.JButton();
        jComboBoxModule = new javax.swing.JComboBox<>();
        jButtonSearchModule = new javax.swing.JButton();
        jLabelStudentName5 = new javax.swing.JLabel();
        jButtonPrint = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jButtonExit.setText("Exit");
        jButtonExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExitActionPerformed(evt);
            }
        });

        jButtonBackToAdmin_Options.setText("Back");
        jButtonBackToAdmin_Options.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackToAdmin_OptionsActionPerformed(evt);
            }
        });

        jButtonClean.setText("Clean");
        jButtonClean.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCleanActionPerformed(evt);
            }
        });

        jButtonSearchCourse.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Images/Search_icon.png"))); // NOI18N
        jButtonSearchCourse.setText("Search");
        jButtonSearchCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSearchCourseActionPerformed(evt);
            }
        });

        jLabelStudentName2.setText("Select a Course:");

        jLabelStudentName3.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabelStudentName3.setText("Enter Results by Class Group");

        jTableResults.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Student", "Assignment 1", "Assignment 2", "Exam", "Result"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableResults);

        jLabelStudentName4.setText("Select a Class:");

        jComboBoxClass.setEnabled(false);

        jButtonSearchClass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Images/Search_icon.png"))); // NOI18N
        jButtonSearchClass.setText("Search");
        jButtonSearchClass.setEnabled(false);
        jButtonSearchClass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSearchClassActionPerformed(evt);
            }
        });

        jComboBoxModule.setEnabled(false);

        jButtonSearchModule.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Images/Search_icon.png"))); // NOI18N
        jButtonSearchModule.setText("Search");
        jButtonSearchModule.setEnabled(false);
        jButtonSearchModule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSearchModuleActionPerformed(evt);
            }
        });

        jLabelStudentName5.setText("Select a Module:");

        jButtonPrint.setText("Print results");
        jButtonPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPrintActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButtonBackToAdmin_Options, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonExit, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelStudentName3, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jComboBoxClass, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonSearchClass))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabelStudentName2, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabelStudentName4, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jComboBoxCourse, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGap(18, 18, 18)
                                    .addComponent(jButtonSearchCourse))
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 679, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jComboBoxModule, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonSearchModule))
                            .addComponent(jLabelStudentName5, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 149, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonPrint, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(82, 82, 82)
                        .addComponent(jButtonClean, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabelStudentName3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelStudentName2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxCourse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonSearchCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelStudentName4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonSearchClass, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxClass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addComponent(jLabelStudentName5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonSearchModule, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxModule, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonClean, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonPrint, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonExit, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonBackToAdmin_Options, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExitActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonExitActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        FillComboBox();
    }//GEN-LAST:event_formWindowActivated

    private void jButtonBackToAdmin_OptionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackToAdmin_OptionsActionPerformed
        if (DataStore.SelectedType.equals("Teacher")) {

            Teacher_Options f = new Teacher_Options();
            f.setVisible(true);
            this.dispose();

        } else {

            Admin_Options f = new Admin_Options();
            f.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_jButtonBackToAdmin_OptionsActionPerformed

    private void jButtonCleanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCleanActionPerformed
    CleanFields();
    }//GEN-LAST:event_jButtonCleanActionPerformed

    private void jButtonSearchCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSearchCourseActionPerformed
        // Enable UI components before processing
        jButtonSearchClass.setEnabled(true);
        jComboBoxClass.setEnabled(true);
        jComboBoxModule.removeAllItems();

        // Clear the combo box to avoid duplicating items from previous searches
        jComboBoxClass.removeAllItems();

        // Get the selected item from the Course combo box
        Object selectedItem = jComboBoxCourse.getSelectedItem();

        if (selectedItem == null || !selectedItem.toString().contains(":")) {
            JOptionPane.showMessageDialog(this, "Please select a  course first.");
            return;
        }

        String selectedCourse = selectedItem.toString();

        try {
            // Parsing the ID from a string format like "1 : Computer Science"
            String selectedText = selectedCourse.trim();
            int colonIdx = selectedText.indexOf(':');
            selectedCourseID = Integer.parseInt(selectedText.substring(0, colonIdx).trim());

            String sql = "SELECT class_group_code FROM class_group WHERE course_id = ?";

            try (Connection con = DriverManager.getConnection(URL, USER, PASSWORD); PreparedStatement ps = con.prepareStatement(sql)) {

                // Bind the selected ID to the first parameter (?) of the query
                ps.setInt(1, selectedCourseID);

                // Execute the query and process the results
                try (ResultSet rs = ps.executeQuery()) {
                    boolean classFound = false;

                    while (rs.next()) {
                        // Extract the class code from the current row
                        int classId = rs.getInt("class_group_code");

                        // Add the result to the combo box
                        jComboBoxClass.addItem("Class: " + classId);
                        classFound = true;
                    }

                    // Optional: notify user if no classes are linked to this course
                    if (!classFound) {
                        JOptionPane.showMessageDialog(this, "No classes found for the selected course.");
                        CleanFields();
                    }
                }
            }
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Error: Invalid course ID format.");
        } catch (SQLException e) {
            // Handle database connection or syntax errors
            JOptionPane.showMessageDialog(this, "Database error: " + e.getMessage());
        }


    }//GEN-LAST:event_jButtonSearchCourseActionPerformed

    private void jButtonSearchClassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSearchClassActionPerformed
        jComboBoxModule.removeAll();
        jButtonSearchCourse.setEnabled(false);
        jButtonSearchClass.setEnabled(false);
        jComboBoxCourse.setEnabled(false);
        jComboBoxClass.setEnabled(false);

        Object selectedClass = jComboBoxClass.getSelectedItem();

        String selectedText = selectedClass.toString().trim();
        String numericOnly = selectedText.replaceAll("[^0-9]", "");
        selectedClassID = Integer.parseInt(numericOnly);

        try {

            String sql = """
        SELECT DISTINCT m.module_name
        FROM class_group cg
        JOIN course_has_module chm ON cg.course_id = chm.course_id
        JOIN module m ON chm.qqi_module_code = m.qqi_module_code
        WHERE cg.class_group_code = ?
    """;

            try (Connection con = DriverManager.getConnection(URL, USER, PASSWORD); PreparedStatement ps = con.prepareStatement(sql)) {

                // Set the Class Group ID parameter
                ps.setInt(1, selectedClassID);

                try (ResultSet rs = ps.executeQuery()) {
                    boolean hasModules = false;

                    while (rs.next()) {
                        // Fetch only the name column
                        String moduleName = rs.getString("module_name");

                        // Add the name directly to the UI component
                        jComboBoxModule.addItem(moduleName);
                        hasModules = true;
                    }

                    if (!hasModules) {
                        JOptionPane.showMessageDialog(this, "No modules associated with this class group.");
                        CleanFields();
                    }
                }
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Database Error: " + e.getMessage());
        }

        jComboBoxModule.setEnabled(true);
        jButtonSearchModule.setEnabled(true);

    }//GEN-LAST:event_jButtonSearchClassActionPerformed

    private void jButtonSearchModuleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSearchModuleActionPerformed

        Object selectedModuleObj = jComboBoxModule.getSelectedItem();
        selectedModule = selectedModuleObj.toString();

        var model = (javax.swing.table.DefaultTableModel) jTableResults.getModel();
        model.setRowCount(0);

        try {

            String sql = """
        SELECT 
            s.first_name, 
            s.surname, 
            a.assignment_1, 
            a.assignment_2, 
            a.exam, 
            a.result
        FROM student s
        JOIN assessment a ON s.student_id = a.student_id
        JOIN module m ON a.qqi_module_code = m.qqi_module_code
        WHERE s.class_group_code = ?
          AND m.module_name = ?;
    """;

            try (Connection con = DriverManager.getConnection(URL, USER, PASSWORD); PreparedStatement ps = con.prepareStatement(sql)) {

                // Set the Class Group ID parameter
                ps.setInt(1, selectedClassID);
                ps.setString(2, selectedModule);

                // Execute the query
                try (ResultSet rs = ps.executeQuery()) {
                    boolean found = false;

                    while (rs.next()) {
                        // Fetch data from the result set
                        String fullName = rs.getString("first_name") + " " + rs.getString("surname");
                        double a1 = rs.getDouble("assignment_1");
                        double a2 = rs.getDouble("assignment_2");
                        double exam = rs.getDouble("exam");
                        double total = rs.getDouble("result");

                        // Add a new row to the table model
                        model.addRow(new Object[]{
                            fullName,
                            a1,
                            a2,
                            exam,
                            total
                        });

                        found = true;
                    }

                    if (!found) {
                        JOptionPane.showMessageDialog(this, "No records found for this class and module.");
                        
                    }
                }

            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Database Error: " + e.getMessage());
        }
        
        jButtonPrint.setEnabled(true);

    }//GEN-LAST:event_jButtonSearchModuleActionPerformed

    private void jButtonPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPrintActionPerformed
        printToPDF();
    }//GEN-LAST:event_jButtonPrintActionPerformed

    private void FillComboBox() {

        var model = (javax.swing.table.DefaultTableModel) jTableResults.getModel();
        model.setRowCount(0);

        jButtonSearchClass.setEnabled(false);
        jComboBoxClass.setEnabled(false);
        jButtonSearchModule.setEnabled(false);
        jComboBoxModule.setEnabled(false);
        jButtonPrint.setEnabled(false);


        String sql = "SELECT * FROM final_project.course";

        try (Connection con = DriverManager.getConnection(URL, USER, PASSWORD); PreparedStatement ps = con.prepareStatement(sql); ResultSet res = ps.executeQuery()) {

            while (res.next()) {
                int id = res.getInt("course_id");
                String qqi = res.getString("qqi_course_code");
                String name = res.getString("course_name");

                String courseName
                        = (name == null ? "" : name) + " "
                        + (qqi == null ? "" : qqi);

                jComboBoxCourse.addItem(id + ": " + courseName);
            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Erro: " + e.getMessage());
        }
        jComboBoxCourse.setSelectedIndex(-1);

    }
    
    private void CleanFields() {
        FillComboBox();

        jButtonSearchCourse.setEnabled(true);
        jComboBoxCourse.setEnabled(true);

        jComboBoxClass.setSelectedIndex(-1);
        jComboBoxClass.setEnabled(false);
        jButtonSearchClass.setEnabled(false);

        jComboBoxModule.setSelectedIndex(-1);
        jComboBoxModule.setEnabled(false);
        jComboBoxModule.removeAllItems();
        jButtonSearchModule.setEnabled(false);
        jButtonPrint.setEnabled(false);
    }

    private void printToPDF() {
        // 1. Basic validation: check if there is data in the table
        if (jTableResults.getRowCount() == 0) {
            JOptionPane.showMessageDialog(this, "Please search for data before printing.");
            return;
        }

        // 2. Prepare the File Chooser
        javax.swing.JFileChooser chooser = new javax.swing.JFileChooser();
        chooser.setDialogTitle("Save Academic Report");

        int currentYear = java.time.LocalDate.now().getYear();

        // Create a safe filename using selected values
        String courseInfo = jComboBoxCourse.getSelectedItem().toString().split(":")[0].trim();
        String fileName = "Report_Class_" + selectedClassID + "_Module" + selectedModule.trim() +" "+ currentYear + ".pdf";
        chooser.setSelectedFile(new java.io.File(fileName));

        if (chooser.showSaveDialog(this) == javax.swing.JFileChooser.APPROVE_OPTION) {
            String path = chooser.getSelectedFile().getAbsolutePath();
            if (!path.endsWith(".pdf")) {
                path += ".pdf";
            }

            try {
                // 3. Initialize iText Document
                com.itextpdf.text.Document document = new com.itextpdf.text.Document();
                com.itextpdf.text.pdf.PdfWriter.getInstance(document, new java.io.FileOutputStream(path));

                document.open();

                // 4. Header Section (Styling)
                com.itextpdf.text.Font titleFont = new com.itextpdf.text.Font(com.itextpdf.text.Font.FontFamily.HELVETICA, 18, com.itextpdf.text.Font.BOLD);
                com.itextpdf.text.Font infoFont = new com.itextpdf.text.Font(com.itextpdf.text.Font.FontFamily.HELVETICA, 12, com.itextpdf.text.Font.NORMAL);

                document.add(new com.itextpdf.text.Paragraph("ACADEMIC RECORD REPORT - " + currentYear, titleFont));
                document.add(new com.itextpdf.text.Paragraph("Course: " + jComboBoxCourse.getSelectedItem().toString(), infoFont));
                document.add(new com.itextpdf.text.Paragraph("Class Group ID: " + selectedClassID, infoFont));
                document.add(new com.itextpdf.text.Paragraph("Module: " + selectedModule, infoFont));
                document.add(new com.itextpdf.text.Paragraph("Date generated: " + java.time.LocalDate.now(), infoFont));
                document.add(new com.itextpdf.text.Paragraph(" ")); // Empty line for spacing

                // 5. Create PDF Table based on JTable model
                javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) jTableResults.getModel();
                com.itextpdf.text.pdf.PdfPTable pdfTable = new com.itextpdf.text.pdf.PdfPTable(model.getColumnCount());
                pdfTable.setWidthPercentage(100); // Table width to fill page

                // Add Header Row to PDF
                for (int i = 0; i < model.getColumnCount(); i++) {
                    com.itextpdf.text.pdf.PdfPCell cell = new com.itextpdf.text.pdf.PdfPCell(new com.itextpdf.text.Phrase(model.getColumnName(i)));
                    cell.setBackgroundColor(com.itextpdf.text.BaseColor.LIGHT_GRAY);
                    cell.setHorizontalAlignment(com.itextpdf.text.Element.ALIGN_CENTER);
                    pdfTable.addCell(cell);
                }

                // Add Data Rows to PDF
                for (int rows = 0; rows < model.getRowCount(); rows++) {
                    for (int cols = 0; cols < model.getColumnCount(); cols++) {
                        Object val = model.getValueAt(rows, cols);
                        pdfTable.addCell(val == null ? "-" : val.toString());
                    }
                }

                document.add(pdfTable);
                document.close();

                JOptionPane.showMessageDialog(this, "PDF Report generated successfully!");

            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Error generating PDF: " + e.getMessage());
                e.printStackTrace();
            }
        }
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Reports_ModuleByClass().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBackToAdmin_Options;
    private javax.swing.JButton jButtonClean;
    private javax.swing.JButton jButtonExit;
    private javax.swing.JButton jButtonPrint;
    private javax.swing.JButton jButtonSearchClass;
    private javax.swing.JButton jButtonSearchCourse;
    private javax.swing.JButton jButtonSearchModule;
    private javax.swing.JComboBox<String> jComboBoxClass;
    private javax.swing.JComboBox<String> jComboBoxCourse;
    private javax.swing.JComboBox<String> jComboBoxModule;
    private javax.swing.JLabel jLabelStudentName2;
    private javax.swing.JLabel jLabelStudentName3;
    private javax.swing.JLabel jLabelStudentName4;
    private javax.swing.JLabel jLabelStudentName5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableResults;
    // End of variables declaration//GEN-END:variables
}
