/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Reports_Frames;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import java.util.List;
import java.util.ArrayList;
import Teacher_Frames.Teacher_Options;
import my.fp.Classes.DataStore;
import Admin_Frames.Admin_Options;
import my.fp.Classes.ClassGroup;

/**
 *
 * @author cjunior
 */
public class Reports_Full_Class_Group extends javax.swing.JFrame {

    private static final String URL = "jdbc:mysql://localhost:3306/final_project";
    private static final String USER = "root";      // seu usuário MySQL
    private static final String PASSWORD = "Root@1234"; // sua senha

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Reports_Full_Class_Group.class.getName());

    /**
     * Creates new form StudentFrame
     */
    public Reports_Full_Class_Group() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonExit = new javax.swing.JButton();
        jButtonClean = new javax.swing.JButton();
        jComboBoxClass = new javax.swing.JComboBox<>();
        jButtonSearch = new javax.swing.JButton();
        jLabelStudentName2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableResults = new javax.swing.JTable();
        jLabelStudentName3 = new javax.swing.JLabel();
        jButtonBack = new javax.swing.JButton();
        jLabelCourse = new javax.swing.JLabel();
        jLabelClassGroup = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jButtonExit.setText("Exit");
        jButtonExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExitActionPerformed(evt);
            }
        });

        jButtonClean.setText("Clean");
        jButtonClean.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCleanActionPerformed(evt);
            }
        });

        jComboBoxClass.setMinimumSize(new java.awt.Dimension(32767, 32767));

        jButtonSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Images/Search_icon.png"))); // NOI18N
        jButtonSearch.setText("Search");
        jButtonSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSearchActionPerformed(evt);
            }
        });

        jLabelStudentName2.setText("Select a Class:");

        jTableResults.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Module", "Student", "Results"
            }
        ));
        jScrollPane1.setViewportView(jTableResults);

        jLabelStudentName3.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabelStudentName3.setText("Full Class Group Reports");

        jButtonBack.setText("Back");
        jButtonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackActionPerformed(evt);
            }
        });

        jLabelCourse.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabelCourse.setText("Course:");
        jLabelCourse.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jLabelClassGroup.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabelClassGroup.setText("Class Group:");
        jLabelClassGroup.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelCourse, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButtonBack, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButtonClean, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonExit, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabelStudentName2, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelStudentName3, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jComboBoxClass, javax.swing.GroupLayout.PREFERRED_SIZE, 559, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jButtonSearch)))
                    .addComponent(jLabelClassGroup, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabelStudentName3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelStudentName2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxClass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabelCourse)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelClassGroup)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonClean, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonExit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonBack, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExitActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonExitActionPerformed

    private void jButtonCleanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCleanActionPerformed
        //Clean Labels
        jLabelCourse.setText("Course:");
        jLabelClassGroup.setText("Class group:");

        // Clean the table
        var model = (javax.swing.table.DefaultTableModel) jTableResults.getModel();
        model.setRowCount(0);

        //Set ComboBoxSelection to "Empty"
        jComboBoxClass.setSelectedIndex(-1);
        
    }//GEN-LAST:event_jButtonCleanActionPerformed

    private void jButtonSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSearchActionPerformed

        // Get the table model and clear existing rows
        var model = (javax.swing.table.DefaultTableModel) jTableResults.getModel();
        model.setRowCount(0);

        // Get the selected object from the ComboBox
        Object selectedItem = jComboBoxClass.getSelectedItem();

        // Validation: Check if something is selected and if it's an instance of Student class
        if (selectedItem == null || !(selectedItem instanceof ClassGroup)) {
            JOptionPane.showMessageDialog(this, "Please select a valid Course and Class.");
            return;
        }

        // Cast the selected item to ClassGroup object to access its methods
        ClassGroup selectedClassGroup = (ClassGroup) selectedItem;
        int classGroupCode = selectedClassGroup.getClassGroupCode();
        jLabelCourse.setText("Course: " + selectedClassGroup.getCourseName() +" "+ selectedClassGroup.getQqiCourseCode());
        jLabelClassGroup.setText("Class group" +": "+ selectedClassGroup.getClassGroupCode());
        // Prepare SQL Query
        String sql = """
        SELECT 
            m.module_name, 
            CONCAT(s.first_name, ' ', s.surname) AS student_name, 
            a.result
        FROM student s
        JOIN class_group cg ON s.class_group_code = cg.class_group_code
        JOIN course_has_module chm ON cg.course_id = chm.course_id
        JOIN module m ON chm.qqi_module_code = m.qqi_module_code
        LEFT JOIN assessment a ON (s.student_id = a.student_id AND m.qqi_module_code = a.qqi_module_code)
        WHERE s.class_group_code = ?
        ORDER BY m.module_name ASC, s.first_name ASC;
    """;

        try (Connection con = DriverManager.getConnection(URL, USER, PASSWORD); PreparedStatement ps = con.prepareStatement(sql)) {

            ps.setInt(1, classGroupCode);

            try (ResultSet rs = ps.executeQuery()) {
                boolean found = false;
                while (rs.next()) {
                    found = true;
                    String module = rs.getString("module_name");
                    String student = rs.getString("student_name");
                    
                    // Use getObject for result to handle NULL values
                    Object result = rs.getObject("result");

                    model.addRow(new Object[]{
                        module,
                        student,
                        (result == null ? "N/A" : result)
                    });
                }

                if (!found) {
                    JOptionPane.showMessageDialog(this, "No students or grades found for this class group.");
                }
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Database Error: " + e.getMessage());
        }


    }//GEN-LAST:event_jButtonSearchActionPerformed

    private void jButtonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackActionPerformed
        if (DataStore.SelectedType.equals("Teacher")) {

            Teacher_Options f = new Teacher_Options();
            f.setVisible(true);
            this.dispose();

        } else {

            Admin_Options f = new Admin_Options();
            f.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_jButtonBackActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        FillComboBox();
    }//GEN-LAST:event_formWindowOpened

    private void FillComboBox() {

        var model = (javax.swing.table.DefaultTableModel) jTableResults.getModel();
        model.setRowCount(0);

        String sql = """
                     SELECT c.course_name, c.qqi_course_code, cg.class_group_code 
                     FROM course c 
                     JOIN class_group cg ON c.course_id = cg.course_id 
                     ORDER BY c.course_name ASC
                    """;

        try (Connection con = DriverManager.getConnection(URL, USER, PASSWORD); PreparedStatement ps = con.prepareStatement(sql); ResultSet rs = ps.executeQuery()) {

            jComboBoxClass.removeAllItems();

            while (rs.next()) {
                // Create the object with data from database
                ClassGroup cg = new ClassGroup(
                        rs.getInt("class_group_code"),
                        rs.getString("course_name"),
                        rs.getString("qqi_course_code")
                );

                // Add the whole object to the ComboBox
                jComboBoxClass.addItem(cg);
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error loading classes: " + e.getMessage());
        }
        jComboBoxClass.setSelectedIndex(-1);

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Reports_Full_Class_Group().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBack;
    private javax.swing.JButton jButtonClean;
    private javax.swing.JButton jButtonExit;
    private javax.swing.JButton jButtonSearch;
    private javax.swing.JComboBox<ClassGroup> jComboBoxClass;
    private javax.swing.JLabel jLabelClassGroup;
    private javax.swing.JLabel jLabelCourse;
    private javax.swing.JLabel jLabelStudentName2;
    private javax.swing.JLabel jLabelStudentName3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableResults;
    // End of variables declaration//GEN-END:variables
}
