/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Admin_Frames;


import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.time.LocalDate;
import javax.swing.JOptionPane;
import javax.swing.DefaultComboBoxModel;
import java.util.Arrays;
import java.util.List;
import my.fp.Classes.Person;
import my.fp.Classes.Student;

/**
 *
 * @author cjunior
 */
public class Admin_ManageStudent extends javax.swing.JFrame {

    private static final String URL = "jdbc:mysql://localhost:3306/final_project";
    private static final String USER = "root";    
    private static final String PASSWORD = "Root@1234";
    private Student currentSelectedStudent;
    private javax.swing.ComboBoxModel<String> originalCountyModel;

    /**
     * Creates new form StaffFrame
     */
    public Admin_ManageStudent() {

        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBoxStudentList = new javax.swing.JComboBox<>();
        jLabelNName8 = new javax.swing.JLabel();
        jButtonBackToAdmin = new javax.swing.JButton();
        jButtonExit = new javax.swing.JButton();
        jLabelNName9 = new javax.swing.JLabel();
        jButtonNew = new javax.swing.JButton();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jPanelEditable = new javax.swing.JPanel();
        jLabelNName = new javax.swing.JLabel();
        jLabelNName1 = new javax.swing.JLabel();
        jLabelNName2 = new javax.swing.JLabel();
        jLabelNName3 = new javax.swing.JLabel();
        jLabelNName4 = new javax.swing.JLabel();
        jLabelNName5 = new javax.swing.JLabel();
        jLabelNName6 = new javax.swing.JLabel();
        jLabelNName7 = new javax.swing.JLabel();
        jTextFieldAddress1 = new javax.swing.JTextField();
        jTextFieldEircode = new javax.swing.JTextField();
        jTextFieldEircode.setEnabled(false);
        jTextFieldEmail = new javax.swing.JTextField();
        jTextFieldEmail.setEnabled(false);
        jTextFieldPhone = new javax.swing.JTextField();
        jComboBoxCounty = new javax.swing.JComboBox<>();
        jButtonDelete = new javax.swing.JButton();
        jButtonDelete.setVisible(true);
        jButtonEdit = new javax.swing.JButton();
        jTextFieldName = new javax.swing.JTextField();
        jTextFieldName.setEnabled(false);
        jTextFieldDoB = new javax.swing.JTextField();
        jTextFieldPPSN = new javax.swing.JTextField();
        jTextFieldPPSN.setEnabled(false);
        jTextFieldAddress2 = new javax.swing.JTextField();
        jTextFieldAddress2.setEnabled(false);
        jLabelNName10 = new javax.swing.JLabel();
        jButtonCancel = new javax.swing.JButton();
        jButtonUpdateInfo = new javax.swing.JButton();
        jTextFieldCourse = new javax.swing.JTextField();
        jTextFieldPPSN.setEnabled(false);
        jLabelNName11 = new javax.swing.JLabel();
        jTextFieldClass = new javax.swing.JTextField();
        jTextFieldPPSN.setEnabled(false);
        jLabelNName12 = new javax.swing.JLabel();
        jLabelTitle = new javax.swing.JLabel();
        jButtonSearch = new javax.swing.JButton();
        jButtonClean = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(617, 619));
        setMinimumSize(new java.awt.Dimension(617, 619));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabelNName8.setText("Select a student from the list");

        jButtonBackToAdmin.setText("Back to Admin");
        jButtonBackToAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackToAdminActionPerformed(evt);
            }
        });

        jButtonExit.setText("Exit");
        jButtonExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExitActionPerformed(evt);
            }
        });

        jLabelNName9.setText("Register a new Student");

        jButtonNew.setText("+ New");
        jButtonNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNewActionPerformed(evt);
            }
        });

        jLabelNName.setText("Name:");

        jLabelNName1.setText("Address:");

        jLabelNName2.setText("County:");

        jLabelNName3.setText("Eircode:");

        jLabelNName4.setText("Email:");

        jLabelNName5.setText("Phone:");

        jLabelNName6.setText("Date of Birth:");

        jLabelNName7.setText("PPSN:");

        jTextFieldAddress1.setEditable(false);
        jTextFieldAddress1.setEnabled(false);

        jTextFieldEircode.setEditable(false);
        jTextFieldEircode.setToolTipText("Only numbers and letters");

        jTextFieldEmail.setEditable(false);

        jTextFieldPhone.setEditable(false);
        jTextFieldPhone.setToolTipText("Only numbers ");
        jTextFieldPhone.setEnabled(false);

        jComboBoxCounty.setEnabled(false);
        jComboBoxCounty.setEnabled(false);

        jButtonDelete.setText("Delete");
        jButtonDelete.setEnabled(false);
        jButtonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteActionPerformed(evt);
            }
        });

        jButtonEdit.setText("Edit");
        jButtonEdit.setEnabled(false);
        jButtonEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditActionPerformed(evt);
            }
        });

        jTextFieldName.setEditable(false);
        jTextFieldName.setToolTipText("");
        jTextFieldName.setMinimumSize(new java.awt.Dimension(2147483647, 2147483647));
        jTextFieldName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNameActionPerformed(evt);
            }
        });

        jTextFieldDoB.setEditable(false);
        jTextFieldDoB.setToolTipText("YYYY-MM-DD");
        jTextFieldDoB.setEnabled(false);

        jTextFieldPPSN.setEditable(false);
        jTextFieldPPSN.setToolTipText("Only numbers and letters");

        jTextFieldAddress2.setEditable(false);

        jLabelNName10.setText("Address Line 2:");

        jButtonCancel.setText("Cancel");
        jButtonCancel.setEnabled(false);
        jButtonUpdateInfo.setVisible(false);
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });

        jButtonUpdateInfo.setText("Update Info.");
        jButtonUpdateInfo.setEnabled(false);
        jButtonUpdateInfo.setVisible(true);
        jButtonUpdateInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUpdateInfoActionPerformed(evt);
            }
        });

        jTextFieldCourse.setEditable(false);
        jTextFieldCourse.setToolTipText("");
        jTextFieldCourse.setEnabled(false);

        jLabelNName11.setText("Course:");

        jTextFieldClass.setEditable(false);
        jTextFieldClass.setToolTipText("");
        jTextFieldClass.setEnabled(false);

        jLabelNName12.setText("Class:");

        javax.swing.GroupLayout jPanelEditableLayout = new javax.swing.GroupLayout(jPanelEditable);
        jPanelEditable.setLayout(jPanelEditableLayout);
        jPanelEditableLayout.setHorizontalGroup(
            jPanelEditableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEditableLayout.createSequentialGroup()
                .addGroup(jPanelEditableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelEditableLayout.createSequentialGroup()
                        .addGroup(jPanelEditableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelEditableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanelEditableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanelEditableLayout.createSequentialGroup()
                                        .addGap(45, 45, 45)
                                        .addGroup(jPanelEditableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jLabelNName1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabelNName2)
                                            .addComponent(jLabelNName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addComponent(jLabelNName3, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addComponent(jLabelNName5, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addGroup(jPanelEditableLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanelEditableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabelNName10)
                                    .addComponent(jLabelNName4)
                                    .addComponent(jLabelNName6)
                                    .addComponent(jLabelNName7))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelEditableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldPPSN)
                            .addComponent(jTextFieldDoB)
                            .addComponent(jTextFieldPhone)
                            .addComponent(jTextFieldEmail)
                            .addComponent(jTextFieldEircode)
                            .addComponent(jComboBoxCounty, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextFieldAddress2)
                            .addComponent(jTextFieldAddress1)
                            .addGroup(jPanelEditableLayout.createSequentialGroup()
                                .addComponent(jTextFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 8, Short.MAX_VALUE))))
                    .addGroup(jPanelEditableLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanelEditableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanelEditableLayout.createSequentialGroup()
                                .addGroup(jPanelEditableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jButtonCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButtonEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(90, 90, 90)
                                .addGroup(jPanelEditableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jButtonDelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButtonUpdateInfo))
                                .addGap(46, 46, 46))
                            .addGroup(jPanelEditableLayout.createSequentialGroup()
                                .addGroup(jPanelEditableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabelNName12)
                                    .addComponent(jLabelNName11))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanelEditableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextFieldCourse, javax.swing.GroupLayout.DEFAULT_SIZE, 352, Short.MAX_VALUE)
                                    .addComponent(jTextFieldClass))))))
                .addContainerGap())
        );
        jPanelEditableLayout.setVerticalGroup(
            jPanelEditableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEditableLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelEditableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNName)
                    .addComponent(jTextFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelEditableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNName1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextFieldAddress1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelEditableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldAddress2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelNName10))
                .addGap(12, 12, 12)
                .addGroup(jPanelEditableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNName2)
                    .addComponent(jComboBoxCounty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelEditableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNName3)
                    .addComponent(jTextFieldEircode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelEditableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNName4)
                    .addComponent(jTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelEditableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelNName5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelEditableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldDoB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelNName6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelEditableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldPPSN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelNName7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelEditableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldCourse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelNName11))
                .addGap(9, 9, 9)
                .addGroup(jPanelEditableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldClass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelNName12))
                .addGap(18, 18, 18)
                .addGroup(jPanelEditableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelEditableLayout.createSequentialGroup()
                        .addComponent(jButtonEdit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonCancel))
                    .addGroup(jPanelEditableLayout.createSequentialGroup()
                        .addComponent(jButtonUpdateInfo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonDelete)))
                .addGap(21, 21, 21))
        );

        jLabelTitle.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabelTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitle.setText("Enter the new info or delete Student");
        jLabelTitle.setVisible(false);

        jLayeredPane1.setLayer(jPanelEditable, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabelTitle, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addGap(103, 103, 103)
                .addComponent(jLabelTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelEditable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelEditable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jButtonSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Images/Search_icon.png"))); // NOI18N
        jButtonSearch.setText("Search");
        jButtonSearch.setMaximumSize(new java.awt.Dimension(72, 23));
        jButtonSearch.setMinimumSize(new java.awt.Dimension(72, 23));
        jButtonSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSearchActionPerformed(evt);
            }
        });

        jButtonClean.setText("Clean");
        jButtonClean.setEnabled(false);
        jButtonClean.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCleanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(jButtonBackToAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonExit, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(9, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelNName9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonNew)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonClean, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelNName8)
                            .addComponent(jComboBoxStudentList, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jButtonSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(87, 87, 87))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelNName8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxStudentList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonClean)
                    .addComponent(jButtonNew)
                    .addComponent(jLabelNName9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonBackToAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonExit, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSearchActionPerformed
        // Get the selected item from the JComboBox
        Object selected = jComboBoxStudentList.getSelectedItem();
        currentSelectedStudent = (Student) selected;

        // Check if the selection is a valid Student object (OOP Principle)
        if (selected instanceof Student selectedStudent) {
            // Retrieve the hidden ID inside the object
            int id = selectedStudent.getStudentId();

            String sql = "SELECT s.*, c.course_name, c.qqi_course_code " +
             "FROM student s " +
             "INNER JOIN class_group cg ON s.class_group_code = cg.class_group_code " +
             "INNER JOIN course c ON cg.course_id = c.course_id " +
             "WHERE s.student_id = ?";

            try (Connection con = DriverManager.getConnection(URL, USER, PASSWORD); PreparedStatement ps = con.prepareStatement(sql)) {

                ps.setInt(1, id);

                try (ResultSet rs = ps.executeQuery()) {
                    if (rs.next()) {
                        // Update the global variable for future Update/Delete operations

                        currentSelectedStudent.setStudentId(rs.getInt("student_id"));

                        // Populate UI labels with full details from the database
                        //Name
                        jTextFieldName.setEnabled(true);                                      //Enable Field
                        currentSelectedStudent.setFirstName(rs.getString("first_name"));        //Set current selected student with db fname
                        currentSelectedStudent.setMiddleName(rs.getString("middle_name"));      //Set Middle name (if exists)
                        currentSelectedStudent.setSurname(rs.getString("surname"));             //Set Surname
                        jTextFieldName.setText(currentSelectedStudent.getFullName());           //Get the full name from Selected Student with method of full name

                        //Email
                        jTextFieldEmail.setEnabled(true);
                        currentSelectedStudent.setEmail(rs.getString("email"));
                        jTextFieldEmail.setText(currentSelectedStudent.getEmail());

                        //Phone
                        jTextFieldPhone.setEnabled(true);
                        currentSelectedStudent.setPhoneNumber(rs.getString("phone_number"));
                        jTextFieldPhone.setText(currentSelectedStudent.getPhoneNumber());

                        //DoB
                        jTextFieldDoB.setEnabled(true);
                        currentSelectedStudent.setDateOfBirth(LocalDate.parse(rs.getString("date_of_birth"))); //Format as Date
                        jTextFieldDoB.setText(currentSelectedStudent.getDateOfBirth().toString());

                        //PPSN
                        jTextFieldPPSN.setEnabled(true);
                        currentSelectedStudent.setPpsn(rs.getString("ppsn"));
                        jTextFieldPPSN.setText(currentSelectedStudent.getPpsn());

                        //County
                        jComboBoxCounty.removeAllItems();
                        currentSelectedStudent.setCounty(rs.getString("county"));
                        jComboBoxCounty.addItem(currentSelectedStudent.getCounty());
                        jComboBoxCounty.setEnabled(true);

                        //Eircode
                        jTextFieldEircode.setEnabled(true);
                        currentSelectedStudent.setEircode(rs.getString("eircode"));
                        jTextFieldEircode.setText(currentSelectedStudent.getEircode());

                        //Address 1
                        jTextFieldAddress1.setEnabled(true);
                        currentSelectedStudent.setAddressLine1(rs.getString("address_line1"));
                        jTextFieldAddress1.setText(currentSelectedStudent.getAddressLine1());

                        //Address 2
                        jTextFieldAddress2.setEnabled(true);
                        currentSelectedStudent.setAddressLine2(rs.getString("address_line2"));
                        jTextFieldAddress2.setText(currentSelectedStudent.getAddressLine2());

                        // Enable/Disable buttons based on state
                        jButtonClean.setEnabled(true);
                        jButtonEdit.setEnabled(true);
                        
                        String courseName = rs.getString("course_name");
                        String qqi = rs.getString("qqi_course_code");
                        
                        jTextFieldCourse.setText(courseName +" "+ qqi);
                        jTextFieldCourse.setToolTipText(courseName +" "+ qqi);
                        jTextFieldClass.setText(rs.getInt("class_group_code")+"");
                        jTextFieldCourse.setEnabled(true);
                        jTextFieldCourse.setEditable(false);
                        jTextFieldClass.setEnabled(true);
                        jTextFieldClass.setEditable(false);
                        
                    }
                }
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(this, "Database error: " + e.getMessage());
            }
        } else {
            JOptionPane.showMessageDialog(this, "Please, select a student member first.");
        }


    }//GEN-LAST:event_jButtonSearchActionPerformed

    private void jButtonCleanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCleanActionPerformed

        jComboBoxStudentList.requestFocus();
        jComboBoxStudentList.setSelectedIndex(-1);

        jTextFieldName.setText("");
        jTextFieldAddress1.setText("");
        jTextFieldAddress2.setText("");
        jComboBoxCounty.removeAllItems();
        jComboBoxCounty.setSelectedIndex(-1);
        jTextFieldEircode.setText("");
        jTextFieldEmail.setText("");
        jTextFieldPhone.setText("");
        jTextFieldDoB.setText("");
        jTextFieldPPSN.setText("");
        jTextFieldCourse.setText("");
        jTextFieldClass.setText("");
        

        jButtonSearch.setEnabled(true);
        jButtonClean.setEnabled(false);
        jButtonUpdateInfo.setEnabled(false);

    }//GEN-LAST:event_jButtonCleanActionPerformed

    private void jButtonExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExitActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonExitActionPerformed

    private void jButtonBackToAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackToAdminActionPerformed
        Admin_Options f = new Admin_Options();
        f.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonBackToAdminActionPerformed

    private void jButtonNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNewActionPerformed
        formWindowOpened(null);

        Admin_Options_RegisterNewStudent f = new Admin_Options_RegisterNewStudent();
        f.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonNewActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // Clear the list to avoid duplication on refresh
        jComboBoxStudentList.removeAllItems();
        jButtonSearch.setEnabled(true);

        String sql = "SELECT student_id, first_name, middle_name, surname FROM student ORDER BY first_name ASC";

        try (Connection con = DriverManager.getConnection(URL, USER, PASSWORD); PreparedStatement ps = con.prepareStatement(sql); ResultSet res = ps.executeQuery()) {

            while (res.next()) {
                
                // Instantiate Staff object using data from the database
                Student s = new Student();
                s.setStudentId(res.getInt("student_id"));
                s.setFirstName(res.getString("first_name"));
                s.setMiddleName(res.getString("middle_name"));
                s.setSurname(res.getString("surname"));

                // Add the object to the ComboBox. 
                // The JComboBox will display the result of s.toString()
                jComboBoxStudentList.addItem(s);
            }

            // Set selection to empty by default
            jComboBoxStudentList.setSelectedIndex(-1);

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error loading student list: " + e.getMessage());
        }

    }//GEN-LAST:event_formWindowOpened

    private void jButtonUpdateInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUpdateInfoActionPerformed
        if (currentSelectedStudent == null) {
            showError("No student selected for update.");
            return;
        }

        if (validateAndFillStaff(currentSelectedStudent)) {

            String sql = "UPDATE student SET address_line1=?, address_line2=?, county=?, eircode=?, email=?, phone_number=? WHERE student_id=?";

            try (Connection con = DriverManager.getConnection(URL, USER, PASSWORD); PreparedStatement ps = con.prepareStatement(sql)) {

                ps.setString(1, currentSelectedStudent.getAddressLine1());
                ps.setString(2, currentSelectedStudent.getAddressLine2());
                ps.setString(3, currentSelectedStudent.getCounty());
                ps.setString(4, currentSelectedStudent.getEircode());
                ps.setString(5, currentSelectedStudent.getEmail());
                ps.setString(6, currentSelectedStudent.getPhoneNumber());
                ps.setInt(7, currentSelectedStudent.getStudentId());

                int rowsUpdated = ps.executeUpdate();

                if (rowsUpdated > 0) {
                    JOptionPane.showMessageDialog(this, "Student updated successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);

                    // --- REFRESH WITH NEW INFOS ---
                    //TextFilds
                    jTextFieldName.setEnabled(true);
                    jTextFieldAddress1.setEditable(false);
                    jTextFieldAddress2.setEditable(false);
                    jComboBoxCounty.removeAllItems();
                    jComboBoxCounty.addItem(currentSelectedStudent.getCounty());
                    jComboBoxCounty.setSelectedItem(currentSelectedStudent);
                    jTextFieldEircode.setEditable(false);
                    jTextFieldEmail.setEditable(false);
                    jTextFieldPhone.setEditable(false);
                    jTextFieldDoB.setEnabled(true);
                    jTextFieldPPSN.setEnabled(true);
                    jTextFieldCourse.setEnabled(true);
                    jTextFieldCourse.setEnabled(true);

                    // Buttons
                    jButtonUpdateInfo.setEnabled(false);
                    jButtonCancel.setEnabled(false);
                    jButtonEdit.setEnabled(true);
                    jButtonDelete.setVisible(false);

                    //labels
                    jLabelTitle.setVisible(false);
                    

                    // Refresh UI with formatted data from the object
                    jTextFieldEircode.setText(currentSelectedStudent.getEircode());
                    jTextFieldPhone.setText(currentSelectedStudent.getPhoneNumber());

                    jButtonSearch.setEnabled(true);
                }

            } catch (SQLException e) {
                showError("Database error during update: " + e.getMessage());
            }
        }

        //Tool Tips off
        ToolTipsNull();
    }//GEN-LAST:event_jButtonUpdateInfoActionPerformed

    private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelActionPerformed

        if (currentSelectedStudent != null) {
            //Fields
            jTextFieldName.setEnabled(true);

            jTextFieldAddress1.setEditable(false);
            jTextFieldAddress1.setText(currentSelectedStudent.getAddressLine1());
            jTextFieldAddress2.setEditable(false);
            jTextFieldAddress2.setText(currentSelectedStudent.getAddressLine2());

            jComboBoxCounty.removeAllItems();
            jComboBoxCounty.addItem(currentSelectedStudent.getCounty());
            jComboBoxCounty.setSelectedItem(currentSelectedStudent);

            jTextFieldEircode.setEditable(false);
            jTextFieldEircode.setText(currentSelectedStudent.getEircode());
            jTextFieldEmail.setEditable(false);
            jTextFieldEmail.setText(currentSelectedStudent.getEmail());
            jTextFieldPhone.setEditable(false);
            jTextFieldPhone.setText(currentSelectedStudent.getPhoneNumber());
            jTextFieldDoB.setEnabled(true);
            jTextFieldPPSN.setEnabled(true);

            jTextFieldCourse.setEnabled(true);
            jTextFieldClass.setEnabled(true);

            //Buttons
            jButtonEdit.setEnabled(true);
            jButtonSearch.setEnabled(true);
            jButtonUpdateInfo.setEnabled(false);
            jButtonDelete.setEnabled(false);
            jButtonCancel.setEnabled(false);

            //Labels
            jLabelTitle.setVisible(false);
           

            //Tool Tips
            ToolTipsNull();
            
        } else {

            //If theres no currentSelectedStudent

            //Hide Labels
            formWindowOpened(null);
            jLabelTitle.setVisible(false);
            

        }

    }//GEN-LAST:event_jButtonCancelActionPerformed

    private void jTextFieldNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNameActionPerformed

    private void jButtonEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditActionPerformed
        //Instructions
        jLabelTitle.setVisible(true);
        jLabelTitle.setText("Enter the new info or delete Student");
       

        //Buttons
        jButtonDelete.setEnabled(true);
        jButtonDelete.setVisible(true);
        jButtonUpdateInfo.setEnabled(true);
        jButtonUpdateInfo.setVisible(true);
        jButtonCancel.setEnabled(true);
        jButtonEdit.setEnabled(false);
        jButtonClean.setEnabled(false);
        jButtonSearch.setEnabled(false);

        //Non Editable Fields
        jTextFieldName.setEnabled(false);
        jTextFieldDoB.setEnabled(false);
        jTextFieldPPSN.setEnabled(false);
        jTextFieldCourse.setEnabled(false);
        jTextFieldClass.setEnabled(false);
        

        //Editable Fields
        jTextFieldAddress1.setEditable(true);
        jTextFieldAddress2.setEditable(true);
        jTextFieldEircode.setEditable(true);
        jTextFieldEmail.setEditable(true);
        jTextFieldPhone.setEditable(true);

        //ComboBox Counties
        String countyFromDB = jComboBoxCounty.getSelectedItem().toString();
        jComboBoxCounty.setSelectedItem(countyFromDB);
        populateCounties(jComboBoxCounty);

        //Tool Tips on
        jTextFieldName.setToolTipText("Is not possible change the name. Delete Student instead");
        jTextFieldDoB.setToolTipText("Is not possible change de Date of Birth. Delete Student instead.");
        jTextFieldPPSN.setToolTipText("Is not possible change the PPSN. Delete Student Instead.");
        jTextFieldCourse.setToolTipText("Is not possible change the curent course. Delete Student Instead.");

    }//GEN-LAST:event_jButtonEditActionPerformed

    private void jButtonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteActionPerformed
        if (currentSelectedStudent == null) {
            showError("Please select a student  first.");
            return;
        }

        // String Confirmation message
        String message = "Are you sure you want to delete " + currentSelectedStudent.getFullName() + "?";
        String title = "Confirm Deletion";

        // PopUp
        int response = JOptionPane.showConfirmDialog(null, message, title, JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);

        // If yes
        if (response == JOptionPane.YES_OPTION) {

            String sql = "DELETE FROM student WHERE student_id = ?";

            try (Connection con = DriverManager.getConnection(URL, USER, PASSWORD); PreparedStatement ps = con.prepareStatement(sql)) {

                ps.setInt(1, currentSelectedStudent.getStudentId());

                int rowsDeleted = ps.executeUpdate();

                if (rowsDeleted > 0) {
                    JOptionPane.showMessageDialog(this, "Student deleted successfully.");

                    // refresh page
                    jButtonCleanActionPerformed(null);
                    formWindowOpened(null);

                    jTextFieldName.setEnabled(true);
                    jTextFieldName.setEditable(false);
                    jTextFieldAddress1.setEditable(false);
                    jTextFieldAddress2.setEditable(false);
                    jTextFieldEircode.setEditable(false);
                    jTextFieldEmail.setEditable(false);
                    jTextFieldPhone.setEditable(false);
                    jTextFieldDoB.setEnabled(true);
                    jTextFieldDoB.setEditable(false);
                    jTextFieldPPSN.setEnabled(true);
                    jTextFieldPPSN.setEditable(false);
                    jTextFieldCourse.setEnabled(true);
                    jTextFieldCourse.setEditable(false);

                    jButtonCancel.setEnabled(false);
                    jButtonDelete.setEnabled(false);

                    

                    jLabelTitle.setVisible(false);

                }

            } catch (SQLException e) {
                showError("Error deleting from database: " + e.getMessage());
            }
        }

        //Tool Tips off
        ToolTipsNull();
    }//GEN-LAST:event_jButtonDeleteActionPerformed

    public void populateCounties(javax.swing.JComboBox<String> comboBox) {
        // 1. Store the current county retrieved from the database
        String currentCounty = (String) comboBox.getSelectedItem();

        // 2. Full list of Republic of Ireland counties
        List<String> allCounties = Arrays.asList(
                "Carlow", "Cavan", "Clare", "Cork", "Donegal", "Dublin", "Galway",
                "Kerry", "Kildare", "Kilkenny", "Laois", "Leitrim", "Limerick",
                "Longford", "Louth", "Mayo", "Meath", "Monaghan", "Offaly",
                "Roscommon", "Sligo", "Tipperary", "Waterford", "Westmeath",
                "Wexford", "Wicklow"
        );

        // 3. Create a new model to manage the data
        DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>();

        // 4. Add the database value first (so it stays selected)
        if (currentCounty != null && !currentCounty.isEmpty()) {
            model.addElement(currentCounty);
        }

        // 5. Add the remaining counties, avoiding the one already added
        for (String county : allCounties) {
            if (!county.equalsIgnoreCase(currentCounty)) {
                model.addElement(county);
            }
        }

        // 6. Apply the populated model back to the JComboBox
        comboBox.setModel(model);

        // 7. Force the selection to the first item (the database value)
        if (model.getSize() > 0) {
            comboBox.setSelectedIndex(0);
        }
    }

    private boolean validateAndFillStaff(Person existingStudent) {
        
        String address1 = jTextFieldAddress1.getText().trim();
        String address2 = jTextFieldAddress2.getText().trim();
        String county = jComboBoxCounty.getSelectedItem().toString();
        String eircode = jTextFieldEircode.getText().trim().replaceAll("\\s+", "").toUpperCase();
        String email = jTextFieldEmail.getText().trim();
        String phone = jTextFieldPhone.getText().trim();

        // 2. Validations
        if (address1.isEmpty() || eircode.isEmpty() || email.isEmpty() || phone.isEmpty()) {
            showError("All required fields must be filled.");
            return false;
        }

        // Email
        if (!email.contains("@") || !email.contains(".")) {
            showError("Invalid email format.");
            return false;
        }

        // Phone 
        if (phone.length() < 7 || !phone.matches("[0-9]+")) {
            showError("Phone must be at least 7 digits and contain only numbers.");
            return false;
        }

        // Eircode 
        if (!eircode.matches("^[A-Z0-9]{7}$")) {
            showError("Eircode must be exactly 7 alphanumeric characters.");
            return false;
        }

        //Update validations if pass
        existingStudent.setAddressLine1(address1);
        existingStudent.setAddressLine2(address2);
        existingStudent.setCounty(county);
        existingStudent.setEircode(eircode);
        existingStudent.setEmail(email);
        existingStudent.setPhoneNumber(phone);

        return true;
    }
    

    private void ToolTipsNull() {
        //Tool Tips
        jTextFieldName.setToolTipText(null);
        jTextFieldDoB.setToolTipText(null);
        jTextFieldPPSN.setToolTipText(null);
        jTextFieldCourse.setToolTipText(null);

    }

    // Método auxiliar para não repetir o JOptionPane toda hora
    private void showError(String message) {
        JOptionPane.showMessageDialog(null, message, "Validation Error", JOptionPane.WARNING_MESSAGE);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        java.awt.EventQueue.invokeLater(() -> new Admin_ManageStudent().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBackToAdmin;
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonClean;
    private javax.swing.JButton jButtonDelete;
    private javax.swing.JButton jButtonEdit;
    private javax.swing.JButton jButtonExit;
    private javax.swing.JButton jButtonNew;
    private javax.swing.JButton jButtonSearch;
    private javax.swing.JButton jButtonUpdateInfo;
    private javax.swing.JComboBox<String> jComboBoxCounty;
    private javax.swing.JComboBox<Student> jComboBoxStudentList;
    private javax.swing.JLabel jLabelNName;
    private javax.swing.JLabel jLabelNName1;
    private javax.swing.JLabel jLabelNName10;
    private javax.swing.JLabel jLabelNName11;
    private javax.swing.JLabel jLabelNName12;
    private javax.swing.JLabel jLabelNName2;
    private javax.swing.JLabel jLabelNName3;
    private javax.swing.JLabel jLabelNName4;
    private javax.swing.JLabel jLabelNName5;
    private javax.swing.JLabel jLabelNName6;
    private javax.swing.JLabel jLabelNName7;
    private javax.swing.JLabel jLabelNName8;
    private javax.swing.JLabel jLabelNName9;
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanelEditable;
    private javax.swing.JTextField jTextFieldAddress1;
    private javax.swing.JTextField jTextFieldAddress2;
    private javax.swing.JTextField jTextFieldClass;
    private javax.swing.JTextField jTextFieldCourse;
    private javax.swing.JTextField jTextFieldDoB;
    private javax.swing.JTextField jTextFieldEircode;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldName;
    private javax.swing.JTextField jTextFieldPPSN;
    private javax.swing.JTextField jTextFieldPhone;
    // End of variables declaration//GEN-END:variables
}
