/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Admin_Frames;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import my.fp.Classes.Student;
import my.fp.Classes.ClassGroup;

/**
 *
 * @author cjunior
 */
public class Admin_Options_RegisterNewStudent extends javax.swing.JFrame {

    private static final String URL = "jdbc:mysql://localhost:3306/final_project";
    private static final String USER = "root";      // seu usuário MySQL
    private static final String PASSWORD = "Root@1234"; // sua senha

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Admin_Options_RegisterNewStudent.class.getName());

    /**
     * Creates new form StaffFrame
     */
    public Admin_Options_RegisterNewStudent() {

        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelNName8 = new javax.swing.JLabel();
        jButtonBack = new javax.swing.JButton();
        jButtonExit = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jTextFieldPhone = new javax.swing.JTextField();
        jTextFieldPPSN = new javax.swing.JTextField();
        jComboBoxCounty = new javax.swing.JComboBox<>();
        jTextFieldDoBDay = new javax.swing.JTextField();
        jTextFieldFirstName = new javax.swing.JTextField();
        jButtonSaveNew = new javax.swing.JButton();
        jTextFieldMiddleName = new javax.swing.JTextField();
        jTextFieldDoBMonth = new javax.swing.JTextField();
        jTextFieldSurname = new javax.swing.JTextField();
        jTextFieldDoBYear = new javax.swing.JTextField();
        jLabelNName9 = new javax.swing.JLabel();
        jLabelNName10 = new javax.swing.JLabel();
        jLabelNName11 = new javax.swing.JLabel();
        jTextFieldAddressLine1 = new javax.swing.JTextField();
        jTextFieldEmail = new javax.swing.JTextField();
        jTextFieldEircode = new javax.swing.JTextField();
        jLabelNName = new javax.swing.JLabel();
        jLabelNName13 = new javax.swing.JLabel();
        jLabelNName14 = new javax.swing.JLabel();
        jLabelNName1 = new javax.swing.JLabel();
        jTextFieldAddressLine2 = new javax.swing.JTextField();
        jLabelNName12 = new javax.swing.JLabel();
        jLabelNName3 = new javax.swing.JLabel();
        jLabelNName2 = new javax.swing.JLabel();
        jLabelNName4 = new javax.swing.JLabel();
        jLabelNName5 = new javax.swing.JLabel();
        jLabelNName6 = new javax.swing.JLabel();
        jLabelNName7 = new javax.swing.JLabel();
        jButtonClean = new javax.swing.JButton();
        jLabelTitle = new javax.swing.JLabel();
        jComboBoxClasseGroup = new javax.swing.JComboBox<>();
        jLabelNName15 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(617, 619));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabelNName8.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabelNName8.setText("Register New Student");

        jButtonBack.setText("Back");
        jButtonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackActionPerformed(evt);
            }
        });

        jButtonExit.setText("Exit");
        jButtonExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExitActionPerformed(evt);
            }
        });

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextFieldPhone.setForeground(new java.awt.Color(153, 153, 153));
        jTextFieldPhone.setText("000000000");
        jTextFieldPhone.setToolTipText("Only numbers. No Spaces.");
        jTextFieldPhone.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldPhoneFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldPhoneFocusLost(evt);
            }
        });
        jTextFieldPhone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPhoneActionPerformed(evt);
            }
        });
        jPanel2.add(jTextFieldPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 259, 341, -1));

        jTextFieldPPSN.setToolTipText("Only numbers and letters.");
        jPanel2.add(jTextFieldPPSN, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 288, 341, -1));

        jComboBoxCounty.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Carlow", "Cavan", "Clare", "Cork", "Donegal", "Dublin", "Galway", "Kerry", "Kildare", "Kilkenny", "Laois", "Leitrim", "Limerick", "Longford", "Louth", "Mayo", "Meath", "Monaghan", "Offaly", "Roscommon", "Sligo", "Tipperary", "Waterford", "Westmeath", "Wexford", "Wicklow" }));
        jComboBoxCounty.setSelectedIndex(-1);
        jComboBoxCounty.setToolTipText("Selec a county from the list");
        jComboBoxCounty.setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));
        jComboBoxCounty.setMinimumSize(new java.awt.Dimension(2147483647, 2147483647));
        jPanel2.add(jComboBoxCounty, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 201, 341, -1));

        jTextFieldDoBDay.setForeground(new java.awt.Color(153, 153, 153));
        jTextFieldDoBDay.setText("XX");
        jTextFieldDoBDay.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldDoBDayFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldDoBDayFocusLost(evt);
            }
        });
        jTextFieldDoBDay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDoBDayActionPerformed(evt);
            }
        });
        jPanel2.add(jTextFieldDoBDay, new org.netbeans.lib.awtextra.AbsoluteConstraints(212, 318, 35, -1));

        jTextFieldFirstName.setMinimumSize(new java.awt.Dimension(2147483647, 2147483647));
        jPanel2.add(jTextFieldFirstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 29, 341, -1));

        jButtonSaveNew.setText("Save");
        jButtonSaveNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaveNewActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonSaveNew, new org.netbeans.lib.awtextra.AbsoluteConstraints(339, 403, 87, -1));
        jPanel2.add(jTextFieldMiddleName, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 58, 341, -1));

        jTextFieldDoBMonth.setForeground(new java.awt.Color(153, 153, 153));
        jTextFieldDoBMonth.setText("XX");
        jTextFieldDoBMonth.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldDoBMonthFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldDoBMonthFocusLost(evt);
            }
        });
        jTextFieldDoBMonth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDoBMonthActionPerformed(evt);
            }
        });
        jPanel2.add(jTextFieldDoBMonth, new org.netbeans.lib.awtextra.AbsoluteConstraints(276, 318, 35, -1));
        jPanel2.add(jTextFieldSurname, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 87, 341, -1));

        jTextFieldDoBYear.setForeground(new java.awt.Color(153, 153, 153));
        jTextFieldDoBYear.setText("XXXX");
        jTextFieldDoBYear.setMaximumSize(new java.awt.Dimension(64, 23));
        jTextFieldDoBYear.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldDoBYearFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldDoBYearFocusLost(evt);
            }
        });
        jTextFieldDoBYear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDoBYearActionPerformed(evt);
            }
        });
        jPanel2.add(jTextFieldDoBYear, new org.netbeans.lib.awtextra.AbsoluteConstraints(343, 317, 47, 25));

        jLabelNName9.setText("D");
        jPanel2.add(jLabelNName9, new org.netbeans.lib.awtextra.AbsoluteConstraints(197, 321, -1, -1));

        jLabelNName10.setText("M");
        jPanel2.add(jLabelNName10, new org.netbeans.lib.awtextra.AbsoluteConstraints(259, 321, -1, -1));

        jLabelNName11.setText("Y");
        jPanel2.add(jLabelNName11, new org.netbeans.lib.awtextra.AbsoluteConstraints(329, 321, -1, -1));

        jTextFieldAddressLine1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldAddressLine1ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextFieldAddressLine1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 116, 341, -1));

        jTextFieldEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldEmailActionPerformed(evt);
            }
        });
        jPanel2.add(jTextFieldEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 230, 341, -1));

        jTextFieldEircode.setForeground(new java.awt.Color(153, 153, 153));
        jTextFieldEircode.setText("H91PHK1");
        jTextFieldEircode.setToolTipText("Only numbers and letters");
        jTextFieldEircode.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldEircodeFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldEircodeFocusLost(evt);
            }
        });
        jPanel2.add(jTextFieldEircode, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 172, 341, -1));

        jLabelNName.setText("First name:");
        jPanel2.add(jLabelNName, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 32, -1, -1));

        jLabelNName13.setText("Middle name:");
        jPanel2.add(jLabelNName13, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 61, -1, -1));

        jLabelNName14.setText("Surname:");
        jPanel2.add(jLabelNName14, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, -1, -1));

        jLabelNName1.setText("Address Line 1:");
        jPanel2.add(jLabelNName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 119, -1, -1));

        jTextFieldAddressLine2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldAddressLine2ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextFieldAddressLine2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 145, 341, -1));

        jLabelNName12.setText("Address Line 2:");
        jPanel2.add(jLabelNName12, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 148, -1, -1));

        jLabelNName3.setText("Eircode:");
        jPanel2.add(jLabelNName3, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 175, -1, -1));

        jLabelNName2.setText("County:");
        jPanel2.add(jLabelNName2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 204, -1, -1));

        jLabelNName4.setText("Email:");
        jPanel2.add(jLabelNName4, new org.netbeans.lib.awtextra.AbsoluteConstraints(69, 233, -1, -1));

        jLabelNName5.setText("Phone:");
        jPanel2.add(jLabelNName5, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 262, -1, -1));

        jLabelNName6.setText("Date of Birth:");
        jPanel2.add(jLabelNName6, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 321, -1, -1));

        jLabelNName7.setText("PPSN:");
        jPanel2.add(jLabelNName7, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 291, -1, -1));

        jButtonClean.setText("Clean");
        jButtonClean.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCleanActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonClean, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 403, 83, -1));

        jLabelTitle.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabelTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitle.setText("Add New Student");
        jLabelTitle.setVisible(false);
        jPanel2.add(jLabelTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(165, 6, 223, -1));

        jComboBoxClasseGroup.setFont(new java.awt.Font("Helvetica Neue", 0, 10)); // NOI18N
        jComboBoxClasseGroup.setToolTipText("");
        jComboBoxClasseGroup.setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));
        jComboBoxClasseGroup.setMinimumSize(new java.awt.Dimension(2147483647, 2147483647));
        jComboBoxClasseGroup.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxClasseGroupItemStateChanged(evt);
            }
        });
        jPanel2.add(jComboBoxClasseGroup, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 350, 340, 30));

        jLabelNName15.setText("Classe group:");
        jPanel2.add(jLabelNName15, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 363, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelNName8)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addComponent(jButtonBack, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonExit, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(108, 108, 108))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(53, Short.MAX_VALUE)
                .addComponent(jLabelNName8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonBack, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonExit, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated

    }//GEN-LAST:event_formWindowActivated

    private void jButtonExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExitActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonExitActionPerformed

    private void jButtonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackActionPerformed
        Admin_ManageStudent f = new Admin_ManageStudent();
        f.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonBackActionPerformed

    private void jButtonCleanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCleanActionPerformed
        jTextFieldFirstName.setText("");
        jTextFieldMiddleName.setText("");
        jTextFieldSurname.setText("");
        jTextFieldAddressLine1.setText("");
        jTextFieldAddressLine2.setText("");
        jTextFieldEircode.setText("H91PHK1");
        jTextFieldEircode.setForeground(java.awt.Color.GRAY);
        jComboBoxCounty.setSelectedIndex(-1);
        jTextFieldEmail.setText("");
        jTextFieldPhone.setText("0000000000");
        jTextFieldPhone.setForeground(java.awt.Color.GRAY);
        jTextFieldPPSN.setText("");
        jTextFieldDoBDay.setText("XX");
        jTextFieldDoBDay.setForeground(java.awt.Color.GRAY);
        jTextFieldDoBMonth.setText("XX");
        jTextFieldDoBMonth.setForeground(java.awt.Color.GRAY);
        jTextFieldDoBYear.setText("XXXX");
        jTextFieldDoBYear.setForeground(java.awt.Color.GRAY);
        jComboBoxClasseGroup.setSelectedItem(null);

    }//GEN-LAST:event_jButtonCleanActionPerformed

    private void jTextFieldAddressLine2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldAddressLine2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldAddressLine2ActionPerformed

    private void jTextFieldEircodeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldEircodeFocusLost
        if (!jTextFieldEircode.getText().equals("H91PHK1")) {

            if (jTextFieldEircode.getText().trim().isEmpty()) {
                jTextFieldEircode.setText("H91PHK1");
                jTextFieldEircode.setForeground(java.awt.Color.GRAY);
            }
        }
    }//GEN-LAST:event_jTextFieldEircodeFocusLost

    private void jTextFieldEircodeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldEircodeFocusGained
        jTextFieldEircode.setText("");
        jTextFieldEircode.setForeground(java.awt.Color.BLACK);
    }//GEN-LAST:event_jTextFieldEircodeFocusGained

    private void jTextFieldEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldEmailActionPerformed

    }//GEN-LAST:event_jTextFieldEmailActionPerformed

    private void jTextFieldAddressLine1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldAddressLine1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldAddressLine1ActionPerformed

    private void jTextFieldDoBYearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDoBYearActionPerformed

    }//GEN-LAST:event_jTextFieldDoBYearActionPerformed

    private void jTextFieldDoBYearFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldDoBYearFocusLost
        if (!jTextFieldDoBYear.getText().equals("XXXX")) {

            if (jTextFieldDoBYear.getText().trim().isEmpty()) {
                jTextFieldDoBYear.setText("XXXX");
                jTextFieldDoBYear.setForeground(java.awt.Color.GRAY);
            }
        }
    }//GEN-LAST:event_jTextFieldDoBYearFocusLost

    private void jTextFieldDoBYearFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldDoBYearFocusGained
        jTextFieldDoBYear.setText("");
        jTextFieldDoBYear.setForeground(java.awt.Color.BLACK);
    }//GEN-LAST:event_jTextFieldDoBYearFocusGained

    private void jTextFieldDoBMonthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDoBMonthActionPerformed

    }//GEN-LAST:event_jTextFieldDoBMonthActionPerformed

    private void jTextFieldDoBMonthFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldDoBMonthFocusLost
        if (!jTextFieldDoBMonth.getText().equals("XX")) {

            if (jTextFieldDoBMonth.getText().trim().isEmpty()) {
                jTextFieldDoBMonth.setText("XX");
                jTextFieldDoBMonth.setForeground(java.awt.Color.GRAY);
            }
        }
    }//GEN-LAST:event_jTextFieldDoBMonthFocusLost

    private void jTextFieldDoBMonthFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldDoBMonthFocusGained
        jTextFieldDoBMonth.setText("");
        jTextFieldDoBMonth.setForeground(java.awt.Color.BLACK);
    }//GEN-LAST:event_jTextFieldDoBMonthFocusGained

    private void jButtonSaveNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveNewActionPerformed
        if (validateFields()) {
            //New object instance
            Student s = new Student();

            ClassGroup selectedGroup;
            if (jComboBoxClasseGroup.getSelectedItem() instanceof ClassGroup cg) {
                selectedGroup = cg;
                s.setClassGroupCode(selectedGroup.getClassGroupCode());
            } else {
                JOptionPane.showMessageDialog(this, "Please select a valid Class Group.");
                return;
            }

            //Setting new object instances
            s.setFirstName(jTextFieldFirstName.getText().trim());
            s.setMiddleName(jTextFieldMiddleName.getText().trim());
            s.setSurname(jTextFieldSurname.getText().trim());
            s.setAddressLine1(jTextFieldAddressLine1.getText().trim());
            s.setAddressLine2(jTextFieldAddressLine2.getText().trim());
            s.setEircode(jTextFieldEircode.getText().trim().toUpperCase());
            s.setCounty(jComboBoxCounty.getSelectedItem().toString());
            s.setEmail(jTextFieldEmail.getText().trim());
            s.setPhoneNumber(jTextFieldPhone.getText().trim());
            s.setPpsn(jTextFieldPPSN.getText().trim().toUpperCase());

            //Date logic
            int day = Integer.parseInt(jTextFieldDoBDay.getText().trim());
            int month = Integer.parseInt(jTextFieldDoBMonth.getText().trim());
            int year = Integer.parseInt(jTextFieldDoBYear.getText().trim());
            s.setDateOfBirth(java.time.LocalDate.of(year, month, day));

            //Message for confirming new Student
            StringBuilder sb = new StringBuilder();
            sb.append("Are you sure you want to create this new student?\n\n");
            sb.append("Full Name: ").append(s.getFullName()).append("\n");
            sb.append("Address: ").append(s.getAddressLine1()).append(", ").append(s.getAddressLine2()).append("\n");
            sb.append("County: ").append(s.getCounty()).append("\n");
            sb.append("Eircode: ").append(s.getEircode()).append("\n");
            sb.append("Email: ").append(s.getEmail()).append("\n");
            sb.append("Phone: ").append(s.getPhoneNumber()).append("\n");
            sb.append("PPSN: ").append(s.getPpsn()).append("\n");
            sb.append("Date of Birth: ").append(s.getDateOfBirth()).append("\n\n");
            sb.append("Course: ").append(selectedGroup.getCourseName()).append("\n");
            sb.append("QQI Code: ").append(selectedGroup.getQqiCourseCode()).append("\n");
            sb.append("Class Group: ").append(selectedGroup.getClassGroupCode()).append("\n\n");
            sb.append("Proceed with registration?");

            int response = JOptionPane.showConfirmDialog(
                    this,
                    sb.toString(),
                    "Confirm New Staff Registration",
                    JOptionPane.YES_NO_OPTION,
                    JOptionPane.QUESTION_MESSAGE
            );

            if (response == JOptionPane.YES_OPTION) {

                String sql = "INSERT INTO student (first_name, middle_name, surname, address_line1, "
                        + "address_line2, eircode, county, email, phone_number, ppsn, "
                        + "date_of_birth, class_group_code) VALUES (?,?,?,?,?,?,?,?,?,?,?,?)";

                try (Connection con = DriverManager.getConnection(URL, USER, PASSWORD); PreparedStatement ps = con.prepareStatement(sql)) {

                    ps.setString(1, s.getFirstName());
                    ps.setString(2, s.getMiddleName());
                    ps.setString(3, s.getSurname());
                    ps.setString(4, s.getAddressLine1());
                    ps.setString(5, s.getAddressLine2());
                    ps.setString(6, s.getEircode());
                    ps.setString(7, s.getCounty());
                    ps.setString(8, s.getEmail());
                    ps.setString(9, s.getPhoneNumber());
                    ps.setString(10, s.getPpsn());
                    ps.setDate(11, java.sql.Date.valueOf(s.getDateOfBirth()));
                    ps.setInt(12, s.getClassGroupCode());

                    ps.executeUpdate();

                    JOptionPane.showMessageDialog(this, "Student " + s.getFullName() + " registered successfully!");
                    jButtonCleanActionPerformed(null);

                } catch (SQLException e) {
                    JOptionPane.showMessageDialog(this, "Database error: " + e.getMessage());
                }

            } else {
                System.out.println("Registration cancelled by user.");
            }
        }
        
    }//GEN-LAST:event_jButtonSaveNewActionPerformed

    private void jTextFieldDoBDayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDoBDayActionPerformed

    }//GEN-LAST:event_jTextFieldDoBDayActionPerformed

    private void jTextFieldDoBDayFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldDoBDayFocusLost
        if (!jTextFieldDoBDay.getText().equals("XX")) {

            if (jTextFieldDoBDay.getText().trim().isEmpty()) {
                jTextFieldDoBDay.setText("XX");
                jTextFieldDoBDay.setForeground(java.awt.Color.GRAY);
            }
        }
    }//GEN-LAST:event_jTextFieldDoBDayFocusLost

    private void jTextFieldDoBDayFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldDoBDayFocusGained
        jTextFieldDoBDay.setText("");
        jTextFieldDoBDay.setForeground(java.awt.Color.BLACK);
    }//GEN-LAST:event_jTextFieldDoBDayFocusGained

    private void jTextFieldPhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPhoneActionPerformed

    }//GEN-LAST:event_jTextFieldPhoneActionPerformed

    private void jTextFieldPhoneFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldPhoneFocusLost
        if (!jTextFieldPhone.getText().equals("0000000000")) {

            if (jTextFieldPhone.getText().trim().isEmpty()) {
                jTextFieldPhone.setText("0000000000");
                jTextFieldPhone.setForeground(java.awt.Color.GRAY);
            }
        }
    }//GEN-LAST:event_jTextFieldPhoneFocusLost

    private void jTextFieldPhoneFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldPhoneFocusGained
        jTextFieldPhone.setText("");
        jTextFieldPhone.setForeground(java.awt.Color.BLACK);
    }//GEN-LAST:event_jTextFieldPhoneFocusGained

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // SQL query using INNER JOIN
        String sql = "SELECT cg.class_group_code, c.course_name, c.qqi_course_code "
                + "FROM final_project.course c "
                + "INNER JOIN final_project.class_group cg ON c.course_id = cg.course_id "
                + "ORDER BY c.course_name ASC, cg.class_group_code ASC";

        try (Connection con = DriverManager.getConnection(URL, USER, PASSWORD); PreparedStatement ps = con.prepareStatement(sql); ResultSet res = ps.executeQuery()) {

            // Clear the ComboBox before populating
            jComboBoxClasseGroup.removeAllItems();

            while (res.next()) {
                // 1. Extract data from the database
                int groupCode = res.getInt("class_group_code");
                String name = res.getString("course_name");
                String qqi = res.getString("qqi_course_code");

                String displayName = name;
                if (name != null) {
                    String[] words = name.split("\\s+"); // Split by spaces
                    if (words.length > 4) {
                        displayName = words[0] + " " + words[1] + " " + words[2] +" "+ words[3] + "...";
                    }
                }

                // 2. Create the Object (using your constructor)
                ClassGroup cg = new ClassGroup(groupCode, displayName, qqi);

                // 3. Add the WHOLE object to the ComboBox
                // Swing will automatically call cg.toString() to display it
                jComboBoxClasseGroup.addItem(cg);
            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Database Error: " + e.getMessage());
        }

        // Set default selection to empty
        jComboBoxClasseGroup.setSelectedIndex(-1);
    }//GEN-LAST:event_formWindowOpened

    private void jComboBoxClasseGroupItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxClasseGroupItemStateChanged
    if (jComboBoxClasseGroup.getSelectedItem() == null) {
        jComboBoxClasseGroup.setToolTipText(null);

        return;
    }
    jComboBoxClasseGroup.setToolTipText(jComboBoxClasseGroup.getSelectedItem().toString());
    }//GEN-LAST:event_jComboBoxClasseGroupItemStateChanged

    public boolean validateFields() {

        String firstName = jTextFieldFirstName.getText().trim();
        String surname = jTextFieldSurname.getText().trim();
        String addressLine1 = jTextFieldAddressLine1.getText();
        String addressLine2 = jTextFieldAddressLine2.getText();
        String email = jTextFieldEmail.getText().trim();
        String eircode = jTextFieldEircode.getText().trim().toUpperCase();
        String phone = jTextFieldPhone.getText().trim();
        String PPSN = jTextFieldPPSN.getText().trim().toUpperCase();

        if (firstName.isEmpty() || surname.isEmpty()) {
            JOptionPane.showMessageDialog(this, "First Name and Surname are required.");
            return false;
        }

        if (addressLine1.isEmpty() || addressLine2.isEmpty()) {
            JOptionPane.showMessageDialog(this, "A full address is required (Line 1 and 2).");
            return false;
        }

        // Validate ComboBox (Check if a county is selected)
        if (jComboBoxCounty.getSelectedIndex() <= 0) {
            JOptionPane.showMessageDialog(this, "Please select a County.");
            return false;
        }

        String emailRegex = "^[A-Za-z0-9+_.-]+@(.+)$";
        if (!email.matches(emailRegex)) {
            JOptionPane.showMessageDialog(this, "Invalid Email format.");
            return false;
        }

        // Validate Eircode (Irish Format: 7 characters, e.g., D02 X123)
        // Pattern: 1 Letter + 2 Digits/Letters + Space? + 4 Digits/Letters
        String eircodeRegex = "^[A-Z][0-9][0-9W][0-9A-Z]{4}$";
        if (eircode.equals("H91PHK1") || !eircode.matches(eircodeRegex)) {
            JOptionPane.showMessageDialog(this, "Invalid Eircode. Please use a format like A65F123.");
            return false;
        }

        // Validate Phone (Numeric, between 7 and 15 digits)
        // If you have ghost text "000 0000", check for it first
        if (phone.equals("0000000000") || !phone.replaceAll("\\s+", "").matches("\\d{7,15}")) {
            JOptionPane.showMessageDialog(this, "Invalid Phone number. Use only digits.");
            return false;
        }

        if (PPSN.isEmpty() || !PPSN.matches("^[0-9]{7}[A-Z]{1,2}$")) {
            JOptionPane.showMessageDialog(this,
                    "Invalid PPSN. It must be 7 numbers followed by 1 or 2 letters (e.g., 1234567AB).",
                    "Validation Error",
                    JOptionPane.WARNING_MESSAGE);
            return false;
        }

        if (jTextFieldDoBDay.getText().equals("XX") || jTextFieldDoBDay.getText().trim().isEmpty()
                || jTextFieldDoBMonth.getText().equals("XX") || jTextFieldDoBMonth.getText().trim().isEmpty()
                || jTextFieldDoBYear.getText().equals("XXXX") || jTextFieldDoBYear.getText().trim().isEmpty()) {

            JOptionPane.showMessageDialog(this, "Please fill in all Date of Birth fields.");
            return false;
        }

        if (!jTextFieldDoBDay.getText().matches("\\d+")
                || !jTextFieldDoBMonth.getText().matches("\\d+")
                || !jTextFieldDoBYear.getText().matches("\\d+")) {

            JOptionPane.showMessageDialog(this, "Date of Birth must contain only numbers.");
            return false;
        }

        return true;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Admin_Options_RegisterNewStudent().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBack;
    private javax.swing.JButton jButtonClean;
    private javax.swing.JButton jButtonExit;
    private javax.swing.JButton jButtonSaveNew;
    private javax.swing.JComboBox<ClassGroup> jComboBoxClasseGroup;
    private javax.swing.JComboBox<String> jComboBoxCounty;
    private javax.swing.JLabel jLabelNName;
    private javax.swing.JLabel jLabelNName1;
    private javax.swing.JLabel jLabelNName10;
    private javax.swing.JLabel jLabelNName11;
    private javax.swing.JLabel jLabelNName12;
    private javax.swing.JLabel jLabelNName13;
    private javax.swing.JLabel jLabelNName14;
    private javax.swing.JLabel jLabelNName15;
    private javax.swing.JLabel jLabelNName2;
    private javax.swing.JLabel jLabelNName3;
    private javax.swing.JLabel jLabelNName4;
    private javax.swing.JLabel jLabelNName5;
    private javax.swing.JLabel jLabelNName6;
    private javax.swing.JLabel jLabelNName7;
    private javax.swing.JLabel jLabelNName8;
    private javax.swing.JLabel jLabelNName9;
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextFieldAddressLine1;
    private javax.swing.JTextField jTextFieldAddressLine2;
    private javax.swing.JTextField jTextFieldDoBDay;
    private javax.swing.JTextField jTextFieldDoBMonth;
    private javax.swing.JTextField jTextFieldDoBYear;
    private javax.swing.JTextField jTextFieldEircode;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldFirstName;
    private javax.swing.JTextField jTextFieldMiddleName;
    private javax.swing.JTextField jTextFieldPPSN;
    private javax.swing.JTextField jTextFieldPhone;
    private javax.swing.JTextField jTextFieldSurname;
    // End of variables declaration//GEN-END:variables
}
