/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Admin_Frames;


import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.time.LocalDate;
import javax.swing.JOptionPane;
import javax.swing.DefaultComboBoxModel;
import java.util.Arrays;
import java.util.List;
import my.fp.Classes.Person;
import my.fp.Classes.Staff;

/**
 *
 * @author cjunior
 */
public class Admin_ManageStaff extends javax.swing.JFrame {

    private static final String URL = "jdbc:mysql://localhost:3306/final_project";
    private static final String USER = "root";      // seu usuário MySQL
    private static final String PASSWORD = "Root@1234"; // sua senha
    private Staff currentSelectedStaff;
    private javax.swing.ComboBoxModel<String> originalCountyModel;

    /**
     * Creates new form StaffFrame
     */
    public Admin_ManageStaff() {

        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBoxStaffList = new javax.swing.JComboBox<>();
        jLabelNName8 = new javax.swing.JLabel();
        jButtonBackToAdmin = new javax.swing.JButton();
        jButtonExit = new javax.swing.JButton();
        jLabelNName9 = new javax.swing.JLabel();
        jButtonNew = new javax.swing.JButton();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jPanelEditable = new javax.swing.JPanel();
        jLabelNName = new javax.swing.JLabel();
        jLabelNName1 = new javax.swing.JLabel();
        jLabelNName2 = new javax.swing.JLabel();
        jLabelNName3 = new javax.swing.JLabel();
        jLabelNName4 = new javax.swing.JLabel();
        jLabelNName5 = new javax.swing.JLabel();
        jLabelNName6 = new javax.swing.JLabel();
        jLabelNName7 = new javax.swing.JLabel();
        jTextFieldAddress1 = new javax.swing.JTextField();
        jTextFieldEircode = new javax.swing.JTextField();
        jTextFieldEircode.setEnabled(false);
        jTextFieldEmail = new javax.swing.JTextField();
        jTextFieldEmail.setEnabled(false);
        jTextFieldPhone = new javax.swing.JTextField();
        jComboBoxCounty = new javax.swing.JComboBox<>();
        jButtonDelete = new javax.swing.JButton();
        jButtonDelete.setVisible(true);
        jButtonEditStaff = new javax.swing.JButton();
        jTextFieldName = new javax.swing.JTextField();
        jTextFieldName.setEnabled(false);
        jTextFieldDoB = new javax.swing.JTextField();
        jTextFieldPPSN = new javax.swing.JTextField();
        jTextFieldPPSN.setEnabled(false);
        jTextFieldAddress2 = new javax.swing.JTextField();
        jTextFieldAddress2.setEnabled(false);
        jLabelNName10 = new javax.swing.JLabel();
        jLabelEircodeInstructions = new javax.swing.JLabel();
        jLabelEircodeInstructions.setVisible(false);
        jLabelPhoneInstructions = new javax.swing.JLabel();
        jLabelPhoneInstructions.setVisible(false);
        jButtonCancel = new javax.swing.JButton();
        jButtonUpdateInfo = new javax.swing.JButton();
        jLabelTitle = new javax.swing.JLabel();
        jButtonSearch = new javax.swing.JButton();
        jButtonClean = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(617, 619));
        setMinimumSize(new java.awt.Dimension(617, 619));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jComboBoxStaffList.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxStaffListItemStateChanged(evt);
            }
        });
        jComboBoxStaffList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxStaffListActionPerformed(evt);
            }
        });
        jComboBoxStaffList.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jComboBoxStaffListPropertyChange(evt);
            }
        });

        jLabelNName8.setText("Select a staff from the list");

        jButtonBackToAdmin.setText("Back to Admin");
        jButtonBackToAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackToAdminActionPerformed(evt);
            }
        });

        jButtonExit.setText("Exit");
        jButtonExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExitActionPerformed(evt);
            }
        });

        jLabelNName9.setText("Register a new Staff");

        jButtonNew.setText("+ New");
        jButtonNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNewActionPerformed(evt);
            }
        });

        jLabelNName.setText("Name:");

        jLabelNName1.setText("Address:");

        jLabelNName2.setText("County:");

        jLabelNName3.setText("Eircode:");

        jLabelNName4.setText("Email:");

        jLabelNName5.setText("Phone:");

        jLabelNName6.setText("Date of Birth:");

        jLabelNName7.setText("PPSN:");

        jTextFieldAddress1.setEditable(false);
        jTextFieldAddress1.setEnabled(false);

        jTextFieldEircode.setEditable(false);
        jTextFieldEircode.setToolTipText("Only numbers and letters");

        jTextFieldEmail.setEditable(false);

        jTextFieldPhone.setEditable(false);
        jTextFieldPhone.setToolTipText("Only numbers ");
        jTextFieldPhone.setEnabled(false);

        jComboBoxCounty.setEnabled(false);
        jComboBoxCounty.setEnabled(false);

        jButtonDelete.setText("Delete");
        jButtonDelete.setEnabled(false);
        jButtonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteActionPerformed(evt);
            }
        });

        jButtonEditStaff.setText("Edit");
        jButtonEditStaff.setEnabled(false);
        jButtonEditStaff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditStaffActionPerformed(evt);
            }
        });

        jTextFieldName.setEditable(false);
        jTextFieldName.setToolTipText("");
        jTextFieldName.setMinimumSize(new java.awt.Dimension(2147483647, 2147483647));
        jTextFieldName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNameActionPerformed(evt);
            }
        });

        jTextFieldDoB.setEditable(false);
        jTextFieldDoB.setToolTipText("YYYY-MM-DD");
        jTextFieldDoB.setEnabled(false);

        jTextFieldPPSN.setEditable(false);
        jTextFieldPPSN.setToolTipText("Only numbers and letters");

        jTextFieldAddress2.setEditable(false);

        jLabelNName10.setText("Address Line 2:");

        jLabelEircodeInstructions.setFont(new java.awt.Font("Helvetica Neue", 0, 10)); // NOI18N
        jLabelEircodeInstructions.setForeground(new java.awt.Color(255, 0, 0));
        jLabelEircodeInstructions.setText("Only numbers and letters");

        jLabelPhoneInstructions.setFont(new java.awt.Font("Helvetica Neue", 0, 10)); // NOI18N
        jLabelPhoneInstructions.setForeground(new java.awt.Color(255, 0, 0));
        jLabelPhoneInstructions.setText("Only numbers ");

        jButtonCancel.setText("Cancel");
        jButtonCancel.setEnabled(false);
        jButtonUpdateInfo.setVisible(false);
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });

        jButtonUpdateInfo.setText("Update Info.");
        jButtonUpdateInfo.setEnabled(false);
        jButtonUpdateInfo.setVisible(true);
        jButtonUpdateInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUpdateInfoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelEditableLayout = new javax.swing.GroupLayout(jPanelEditable);
        jPanelEditable.setLayout(jPanelEditableLayout);
        jPanelEditableLayout.setHorizontalGroup(
            jPanelEditableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelEditableLayout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addGroup(jPanelEditableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelEditableLayout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(jPanelEditableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButtonCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonEditStaff, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanelEditableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButtonDelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonUpdateInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(13, 13, 13))
                    .addGroup(jPanelEditableLayout.createSequentialGroup()
                        .addGroup(jPanelEditableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanelEditableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanelEditableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanelEditableLayout.createSequentialGroup()
                                        .addGap(17, 17, 17)
                                        .addGroup(jPanelEditableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabelNName)
                                            .addComponent(jLabelNName1)
                                            .addComponent(jLabelNName2)))
                                    .addComponent(jLabelNName3, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addComponent(jLabelNName5, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addComponent(jLabelNName10)
                            .addComponent(jLabelNName4)
                            .addComponent(jLabelNName6)
                            .addComponent(jLabelNName7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelEditableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldDoB, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanelEditableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jTextFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextFieldAddress1)
                                .addComponent(jTextFieldAddress2)
                                .addComponent(jTextFieldEircode, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jTextFieldPhone)
                                .addComponent(jTextFieldEmail, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jComboBoxCounty, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jTextFieldPPSN, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)))
                .addGroup(jPanelEditableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelEircodeInstructions)
                    .addComponent(jLabelPhoneInstructions))
                .addGap(16, 16, 16))
        );
        jPanelEditableLayout.setVerticalGroup(
            jPanelEditableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEditableLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelEditableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNName)
                    .addComponent(jTextFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelEditableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNName1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextFieldAddress1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelEditableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldAddress2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelNName10))
                .addGap(12, 12, 12)
                .addGroup(jPanelEditableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNName2)
                    .addComponent(jComboBoxCounty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelEditableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNName3)
                    .addComponent(jTextFieldEircode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelEircodeInstructions))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelEditableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNName4)
                    .addComponent(jTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelEditableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelPhoneInstructions)
                    .addComponent(jLabelNName5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelEditableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldDoB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelNName6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelEditableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldPPSN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelNName7))
                .addGap(26, 26, 26)
                .addGroup(jPanelEditableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonEditStaff)
                    .addComponent(jButtonUpdateInfo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelEditableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonDelete)
                    .addComponent(jButtonCancel))
                .addGap(32, 32, 32))
        );

        jLabelTitle.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabelTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitle.setText("Enter the new info or delete Staff");
        jLabelTitle.setVisible(false);

        jLayeredPane1.setLayer(jPanelEditable, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabelTitle, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanelEditable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addGap(182, 182, 182)
                        .addComponent(jLabelTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabelTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addComponent(jPanelEditable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jButtonSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Images/Search_icon.png"))); // NOI18N
        jButtonSearch.setText("Search");
        jButtonSearch.setMaximumSize(new java.awt.Dimension(72, 23));
        jButtonSearch.setMinimumSize(new java.awt.Dimension(72, 23));
        jButtonSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSearchActionPerformed(evt);
            }
        });

        jButtonClean.setText("Clean");
        jButtonClean.setEnabled(false);
        jButtonClean.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCleanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(jButtonBackToAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonExit, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(127, 127, 127))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelNName9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonNew)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonClean, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelNName8)
                            .addComponent(jComboBoxStaffList, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jButtonSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(87, 87, 87))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelNName8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxStaffList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonClean)
                    .addComponent(jButtonNew)
                    .addComponent(jLabelNName9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonBackToAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonExit, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSearchActionPerformed
        // Get the selected item from the JComboBox
        Object selected = jComboBoxStaffList.getSelectedItem();
        currentSelectedStaff = (Staff) selected;

        // Check if the selection is a valid Staff object (OOP Principle)
        if (selected instanceof Staff selectedStaff) {
            // Retrieve the hidden ID inside the object
            int id = selectedStaff.getStaffNumber();

            String sql = "SELECT * FROM staff WHERE staff_id = ?";

            try (Connection con = DriverManager.getConnection(URL, USER, PASSWORD); PreparedStatement ps = con.prepareStatement(sql)) {

                ps.setInt(1, id);

                try (ResultSet rs = ps.executeQuery()) {
                    if (rs.next()) {
                        // Update the global variable for future Update/Delete operations
                        currentSelectedStaff.setStaffNumber(rs.getInt("staff_id"));

                        // Populate UI labels with full details from the database
                        //Name
                        jTextFieldName.setEnabled(true);                                      //Enable Field
                        currentSelectedStaff.setFirstName(rs.getString("first_name"));        //Set current selected staff with db fname
                        currentSelectedStaff.setMiddleName(rs.getString("middle_name"));      //Set Middle name (if exists)
                        currentSelectedStaff.setSurname(rs.getString("surname"));             //Set Surname
                        jTextFieldName.setText(currentSelectedStaff.getFullName());           //Get the full name from Selected Staff with method of full name

                        //Email
                        jTextFieldEmail.setEnabled(true);
                        currentSelectedStaff.setEmail(rs.getString("email"));
                        jTextFieldEmail.setText(currentSelectedStaff.getEmail());

                        //Phone
                        jTextFieldPhone.setEnabled(true);
                        currentSelectedStaff.setPhoneNumber(rs.getString("phone_number"));
                        jTextFieldPhone.setText(currentSelectedStaff.getPhoneNumber());

                        //DoB
                        jTextFieldDoB.setEnabled(true);
                        currentSelectedStaff.setDateOfBirth(LocalDate.parse(rs.getString("date_of_birth"))); //Format as Date
                        jTextFieldDoB.setText(currentSelectedStaff.getDateOfBirth().toString());

                        //PPSN
                        jTextFieldPPSN.setEnabled(true);
                        currentSelectedStaff.setPpsn(rs.getString("ppsn"));
                        jTextFieldPPSN.setText(currentSelectedStaff.getPpsn());

                        //County
                        jComboBoxCounty.removeAllItems();
                        currentSelectedStaff.setCounty(rs.getString("county"));
                        jComboBoxCounty.addItem(currentSelectedStaff.getCounty());
                        jComboBoxCounty.setEnabled(true);

                        //Eircode
                        jTextFieldEircode.setEnabled(true);
                        currentSelectedStaff.setEircode(rs.getString("eircode"));
                        jTextFieldEircode.setText(currentSelectedStaff.getEircode());

                        //Address 1
                        jTextFieldAddress1.setEnabled(true);
                        currentSelectedStaff.setAddressLine1(rs.getString("address_line1"));
                        jTextFieldAddress1.setText(currentSelectedStaff.getAddressLine1());

                        //Address 2
                        jTextFieldAddress2.setEnabled(true);
                        currentSelectedStaff.setAddressLine2(rs.getString("address_line2"));
                        jTextFieldAddress2.setText(currentSelectedStaff.getAddressLine2());

                        // Enable/Disable buttons based on state
                        jButtonClean.setEnabled(true);
                        jButtonEditStaff.setEnabled(true);
                        

                    }
                }
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(this, "Database error: " + e.getMessage());
            }
        } else {
            JOptionPane.showMessageDialog(this, "Please, select a staff member first.");
        }


    }//GEN-LAST:event_jButtonSearchActionPerformed

    private void jButtonCleanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCleanActionPerformed

        jComboBoxStaffList.requestFocus();
        jComboBoxStaffList.setSelectedIndex(-1);

        jTextFieldName.setText("");
        jTextFieldAddress1.setText("");
        jTextFieldAddress2.setText("");
        jComboBoxCounty.removeAllItems();
        jComboBoxCounty.setSelectedIndex(-1);
        jTextFieldEircode.setText("");
        jTextFieldEmail.setText("");
        jTextFieldPhone.setText("");
        jTextFieldDoB.setText("");
        jTextFieldPPSN.setText("");

        jButtonSearch.setEnabled(true);
        jButtonClean.setEnabled(false);
        jButtonUpdateInfo.setEnabled(false);

    }//GEN-LAST:event_jButtonCleanActionPerformed

    private void jComboBoxStaffListItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxStaffListItemStateChanged

    }//GEN-LAST:event_jComboBoxStaffListItemStateChanged

    private void jComboBoxStaffListPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jComboBoxStaffListPropertyChange

    }//GEN-LAST:event_jComboBoxStaffListPropertyChange

    private void jButtonExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExitActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonExitActionPerformed

    private void jButtonBackToAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackToAdminActionPerformed
        Admin_Options f = new Admin_Options();
        f.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonBackToAdminActionPerformed

    private void jComboBoxStaffListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxStaffListActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxStaffListActionPerformed

    private void jButtonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteActionPerformed
        if (currentSelectedStaff == null) {
            showError("Please select a staff member first.");
            return;
        }

        // String Confirmation message
        String message = "Are you sure you want to delete " + currentSelectedStaff.getFullName() + "?";
        String title = "Confirm Deletion";

        // PopUp
        int response = JOptionPane.showConfirmDialog(null, message, title, JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);

        // If yes
        if (response == JOptionPane.YES_OPTION) {

            String sql = "DELETE FROM staff WHERE staff_id = ?";

            try (Connection con = DriverManager.getConnection(URL, USER, PASSWORD); PreparedStatement ps = con.prepareStatement(sql)) {

                ps.setInt(1, currentSelectedStaff.getStaffNumber());

                int rowsDeleted = ps.executeUpdate();

                if (rowsDeleted > 0) {
                    JOptionPane.showMessageDialog(this, "Staff deleted successfully.");

                    // refresh page
                    jButtonCleanActionPerformed(null);
                    formWindowOpened(null);
                    jButtonCancelActionPerformed(null);
                }

            } catch (SQLException e) {
                showError("Error deleting from database: " + e.getMessage());
            }
        }

        //Tool Tips off
        ToolTipsNull();
    }//GEN-LAST:event_jButtonDeleteActionPerformed

    private void jButtonNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNewActionPerformed
        formWindowOpened(null);

        Admin_Options_RegisterNewStaff f = new Admin_Options_RegisterNewStaff();
        f.setVisible(true);
        this.dispose();



    }//GEN-LAST:event_jButtonNewActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        
        // Clear the list to avoid duplication on refresh
        jComboBoxStaffList.removeAllItems();
        jButtonSearch.setEnabled(true);

        String sql = "SELECT staff_id, first_name, middle_name, surname FROM staff ORDER BY first_name ASC";

        try (Connection con = DriverManager.getConnection(URL, USER, PASSWORD); PreparedStatement ps = con.prepareStatement(sql); ResultSet res = ps.executeQuery()) {

            while (res.next()) {
                
                // Instantiate Staff object using data from the database
                Staff s = new Staff();
                s.setStaffNumber(res.getInt("staff_id"));
                s.setFirstName(res.getString("first_name"));
                s.setMiddleName(res.getString("middle_name"));
                s.setSurname(res.getString("surname"));

                // Add the object to the ComboBox. 
                // The JComboBox will display the result of s.toString()
                jComboBoxStaffList.addItem(s);
            }

            // Set selection to empty by default
            jComboBoxStaffList.setSelectedIndex(-1);

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error loading staff list: " + e.getMessage());
        }

    }//GEN-LAST:event_formWindowOpened

    private void jButtonEditStaffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditStaffActionPerformed
        //Instructions
        jLabelTitle.setVisible(true);
        jLabelTitle.setText("Enter the new info or delete Staff");
        jLabelEircodeInstructions.setVisible(true);
        jLabelPhoneInstructions.setVisible(true);

        //Buttons
        jButtonDelete.setEnabled(true);
        jButtonDelete.setVisible(true);
        jButtonUpdateInfo.setEnabled(true);
        jButtonUpdateInfo.setVisible(true);
        jButtonCancel.setEnabled(true);
        jButtonEditStaff.setEnabled(false);
        jButtonClean.setEnabled(false);
        jButtonSearch.setEnabled(false);
        

        //Non Editable Fields
        jTextFieldName.setEnabled(false);
        jTextFieldDoB.setEnabled(false);
        jTextFieldPPSN.setEnabled(false);

        //Editable Fields
        jTextFieldAddress1.setEditable(true);
        jTextFieldAddress2.setEditable(true);
        jTextFieldEircode.setEditable(true);
        jTextFieldEmail.setEditable(true);
        jTextFieldPhone.setEditable(true);

        //ComboBox Counties
        String countyFromDB = jComboBoxCounty.getSelectedItem().toString();
        jComboBoxCounty.setSelectedItem(countyFromDB);
        populateCounties(jComboBoxCounty);

        //Tool Tips on
        jTextFieldName.setToolTipText("Is not possible change the name. Delete Staff instead");
        jTextFieldDoB.setToolTipText("Is not possible change de Date of Birth. Delete Staff instead.");
        jTextFieldPPSN.setToolTipText("Is not possible change the PPSN. Delete Staff Instead.");


    }//GEN-LAST:event_jButtonEditStaffActionPerformed

    private void jTextFieldNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNameActionPerformed

    private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelActionPerformed

        if (currentSelectedStaff != null) {
            //Fields
            jTextFieldName.setEnabled(true);

            jTextFieldAddress1.setEditable(false);
            jTextFieldAddress1.setText(currentSelectedStaff.getAddressLine1());
            jTextFieldAddress2.setEditable(false);
            jTextFieldAddress2.setText(currentSelectedStaff.getAddressLine2());

            jComboBoxCounty.removeAllItems();
            jComboBoxCounty.addItem(currentSelectedStaff.getCounty());
            jComboBoxCounty.setSelectedItem(currentSelectedStaff);

            jTextFieldEircode.setEditable(false);
            jTextFieldEircode.setText(currentSelectedStaff.getEircode());
            jTextFieldEmail.setEditable(false);
            jTextFieldEmail.setText(currentSelectedStaff.getEmail());
            jTextFieldPhone.setEditable(false);
            jTextFieldPhone.setText(currentSelectedStaff.getPhoneNumber());
            jTextFieldDoB.setEnabled(true);
            jTextFieldPPSN.setEnabled(true);

            //Buttons
            jButtonEditStaff.setEnabled(true);
            jButtonSearch.setEnabled(true);
            jButtonUpdateInfo.setEnabled(false);
            jButtonDelete.setEnabled(false);
            jButtonDelete.setVisible(false);
            jButtonCancel.setEnabled(false);

            //Labels
            jLabelTitle.setVisible(false);
            jLabelEircodeInstructions.setVisible(false);
            jLabelPhoneInstructions.setVisible(false);

            //Tool Tips
            jTextFieldName.setToolTipText(null);
            jTextFieldDoB.setToolTipText(null);
            jTextFieldPPSN.setToolTipText(null);
        } else {
            
            //If theres no currentSelectedStaff = Cancel come from New Button.
            
            //Hide Labels
            formWindowOpened(null);
            jLabelTitle.setVisible(false);
            jLabelEircodeInstructions.setVisible(false);
            jLabelPhoneInstructions.setVisible(false);
            
            

        }


    }//GEN-LAST:event_jButtonCancelActionPerformed

    private void jButtonUpdateInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUpdateInfoActionPerformed
    if (currentSelectedStaff == null) {
            showError("No staff selected for update.");
            return;
        }

        if (validateAndFillStaff(currentSelectedStaff)) {

            String sql = "UPDATE staff SET address_line1=?, address_line2=?, county=?, eircode=?, email=?, phone_number=? WHERE staff_id=?";

            try (Connection con = DriverManager.getConnection(URL, USER, PASSWORD); PreparedStatement ps = con.prepareStatement(sql)) {

                ps.setString(1, currentSelectedStaff.getAddressLine1());
                ps.setString(2, currentSelectedStaff.getAddressLine2());
                ps.setString(3, currentSelectedStaff.getCounty());
                ps.setString(4, currentSelectedStaff.getEircode());
                ps.setString(5, currentSelectedStaff.getEmail());
                ps.setString(6, currentSelectedStaff.getPhoneNumber());
                ps.setInt(7, currentSelectedStaff.getStaffNumber());

                int rowsUpdated = ps.executeUpdate();

                if (rowsUpdated > 0) {
                    JOptionPane.showMessageDialog(this, "Staff updated successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);

                    // --- REFRESH WITH NEW INFOS ---
                    //TextFilds
                    jTextFieldName.setEnabled(true);
                    jTextFieldAddress1.setEditable(false);
                    jTextFieldAddress2.setEditable(false);
                    jComboBoxCounty.removeAllItems();
                    jComboBoxCounty.addItem(currentSelectedStaff.getCounty());
                    jComboBoxCounty.setSelectedItem(currentSelectedStaff);
                    jTextFieldEircode.setEditable(false);
                    jTextFieldEmail.setEditable(false);
                    jTextFieldPhone.setEditable(false);
                    jTextFieldDoB.setEnabled(true);
                    jTextFieldPPSN.setEnabled(true);

                    // Buttons
                    jButtonUpdateInfo.setEnabled(false);
                    jButtonCancel.setEnabled(false);
                    jButtonEditStaff.setEnabled(true);
                    jButtonDelete.setVisible(false);

                    //labels
                    jLabelTitle.setVisible(false);
                    jLabelEircodeInstructions.setVisible(false);
                    jLabelPhoneInstructions.setVisible(false);

                    // Refresh UI with formatted data from the object
                    jTextFieldEircode.setText(currentSelectedStaff.getEircode());
                    jTextFieldPhone.setText(currentSelectedStaff.getPhoneNumber());

                    jButtonSearch.setEnabled(true);
                }

            } catch (SQLException e) {
                showError("Database error during update: " + e.getMessage());
            }
        }

        //Tool Tips off
        ToolTipsNull();
    }//GEN-LAST:event_jButtonUpdateInfoActionPerformed

    public void populateCounties(javax.swing.JComboBox<String> comboBox) {
        // 1. Store the current county retrieved from the database
        String currentCounty = (String) comboBox.getSelectedItem();

        // 2. Full list of Republic of Ireland counties
        List<String> allCounties = Arrays.asList(
                "Carlow", "Cavan", "Clare", "Cork", "Donegal", "Dublin", "Galway",
                "Kerry", "Kildare", "Kilkenny", "Laois", "Leitrim", "Limerick",
                "Longford", "Louth", "Mayo", "Meath", "Monaghan", "Offaly",
                "Roscommon", "Sligo", "Tipperary", "Waterford", "Westmeath",
                "Wexford", "Wicklow"
        );

        // 3. Create a new model to manage the data
        DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>();

        // 4. Add the database value first (so it stays selected)
        if (currentCounty != null && !currentCounty.isEmpty()) {
            model.addElement(currentCounty);
        }

        // 5. Add the remaining counties, avoiding the one already added
        for (String county : allCounties) {
            if (!county.equalsIgnoreCase(currentCounty)) {
                model.addElement(county);
            }
        }

        // 6. Apply the populated model back to the JComboBox
        comboBox.setModel(model);

        // 7. Force the selection to the first item (the database value)
        if (model.getSize() > 0) {
            comboBox.setSelectedIndex(0);
        }
    }

    private boolean validateAndFillStaff(Person existingStaff) {
        
        String address1 = jTextFieldAddress1.getText().trim();
        String address2 = jTextFieldAddress2.getText().trim();
        String county = jComboBoxCounty.getSelectedItem().toString();
        String eircode = jTextFieldEircode.getText().trim().replaceAll("\\s+", "").toUpperCase();
        String email = jTextFieldEmail.getText().trim();
        String phone = jTextFieldPhone.getText().trim();

        // 2. Validations
        
        if (address1.isEmpty() || eircode.isEmpty() || email.isEmpty() || phone.isEmpty()) {
            showError("All required fields must be filled.");
            return false;
        }

        // Email
        if (!email.contains("@") || !email.contains(".")) {
            showError("Invalid email format.");
            return false;
        }

        // Phone 
        if (phone.length() < 7 || !phone.matches("[0-9]+")) {
            showError("Phone must be at least 7 digits and contain only numbers.");
            return false;
        }

        // Eircode
        if (!eircode.matches("^[A-Z0-9]{7}$")) {
            showError("Eircode must be exactly 7 alphanumeric characters.");
            return false;
        }

        
        existingStaff.setAddressLine1(address1);
        existingStaff.setAddressLine2(address2);
        existingStaff.setCounty(county);
        existingStaff.setEircode(eircode);
        existingStaff.setEmail(email);
        existingStaff.setPhoneNumber(phone);

        return true; // Sucesso!
    }
    

    private void ToolTipsNull() {
        //Tool Tips
        jTextFieldName.setToolTipText(null);
        jTextFieldDoB.setToolTipText(null);
        jTextFieldPPSN.setToolTipText(null);
    }

    // Método auxiliar para não repetir o JOptionPane toda hora
    private void showError(String message) {
        JOptionPane.showMessageDialog(null, message, "Validation Error", JOptionPane.WARNING_MESSAGE);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        java.awt.EventQueue.invokeLater(() -> new Admin_ManageStaff().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBackToAdmin;
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonClean;
    private javax.swing.JButton jButtonDelete;
    private javax.swing.JButton jButtonEditStaff;
    private javax.swing.JButton jButtonExit;
    private javax.swing.JButton jButtonNew;
    private javax.swing.JButton jButtonSearch;
    private javax.swing.JButton jButtonUpdateInfo;
    private javax.swing.JComboBox<String> jComboBoxCounty;
    private javax.swing.JComboBox<Staff> jComboBoxStaffList;
    private javax.swing.JLabel jLabelEircodeInstructions;
    private javax.swing.JLabel jLabelNName;
    private javax.swing.JLabel jLabelNName1;
    private javax.swing.JLabel jLabelNName10;
    private javax.swing.JLabel jLabelNName2;
    private javax.swing.JLabel jLabelNName3;
    private javax.swing.JLabel jLabelNName4;
    private javax.swing.JLabel jLabelNName5;
    private javax.swing.JLabel jLabelNName6;
    private javax.swing.JLabel jLabelNName7;
    private javax.swing.JLabel jLabelNName8;
    private javax.swing.JLabel jLabelNName9;
    private javax.swing.JLabel jLabelPhoneInstructions;
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanelEditable;
    private javax.swing.JTextField jTextFieldAddress1;
    private javax.swing.JTextField jTextFieldAddress2;
    private javax.swing.JTextField jTextFieldDoB;
    private javax.swing.JTextField jTextFieldEircode;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldName;
    private javax.swing.JTextField jTextFieldPPSN;
    private javax.swing.JTextField jTextFieldPhone;
    // End of variables declaration//GEN-END:variables
}
