/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Admin_Frames;

import Login_Frames.Login_Frame;
import Reports_Frames.Reports_ModuleByClass;
import Reports_Frames.Reports_Distinction_Students_by_Module;
import Reports_Frames.Reports_Module_by_AllGroups;
import Reports_Frames.FullStudentReport;
import Reports_Frames.Reports_Full_Class_Group;


/**
 *
 * @author cjunior
 */
public class Admin_Options extends javax.swing.JFrame {

    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Admin_Options.class.getName());

    /**
     * Creates new form LoginFrame
     */
    public Admin_Options() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jButtonBackToLogin = new javax.swing.JButton();
        jButtonManageStaff = new javax.swing.JButton();
        jButtonExit = new javax.swing.JButton();
        jButtonUpdateStudentInfo = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButtonFullStudentRecord = new javax.swing.JButton();
        jButtonModuleResultsByClass = new javax.swing.JButton();
        jButtonModuleResultsAllGroups = new javax.swing.JButton();
        jButtonModuleResultsDistinction = new javax.swing.JButton();
        jButtonModuleResultsFullClass = new javax.swing.JButton();
        jButtonCoursesAndModules = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jButtonBackToLogin.setText("Logout");
        jButtonBackToLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackToLoginActionPerformed(evt);
            }
        });

        jButtonManageStaff.setText("Manage Staff");
        jButtonManageStaff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonManageStaffActionPerformed(evt);
            }
        });

        jButtonExit.setText("Exit");
        jButtonExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExitActionPerformed(evt);
            }
        });

        jButtonUpdateStudentInfo.setText("Manage Student");
        jButtonUpdateStudentInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUpdateStudentInfoActionPerformed(evt);
            }
        });

        jLabel2.setText("View Reports:");

        jButtonFullStudentRecord.setText("Full Student Record ");
        jButtonFullStudentRecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFullStudentRecordActionPerformed(evt);
            }
        });

        jButtonModuleResultsByClass.setText("Module Results (by Class Group)");
        jButtonModuleResultsByClass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModuleResultsByClassActionPerformed(evt);
            }
        });

        jButtonModuleResultsAllGroups.setText("Module Results (All Groups)");
        jButtonModuleResultsAllGroups.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModuleResultsAllGroupsActionPerformed(evt);
            }
        });

        jButtonModuleResultsDistinction.setText("Distinction Students by Module");
        jButtonModuleResultsDistinction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModuleResultsDistinctionActionPerformed(evt);
            }
        });

        jButtonModuleResultsFullClass.setText("Full Class Group Report");
        jButtonModuleResultsFullClass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModuleResultsFullClassActionPerformed(evt);
            }
        });

        jButtonCoursesAndModules.setText("Courses and Modules");
        jButtonCoursesAndModules.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCoursesAndModulesActionPerformed(evt);
            }
        });

        jLabel3.setText("Admin Functions:");

        jLabel4.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel4.setText("Logged in as Administrator");

        jLabel5.setText("View Course details");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(75, 75, 75)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButtonUpdateStudentInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButtonManageStaff, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButtonCoursesAndModules, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButtonBackToLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(163, 163, 163)
                                .addComponent(jLabel3)))
                        .addGap(42, 42, 42))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(118, 118, 118)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jButtonFullStudentRecord, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonModuleResultsByClass, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonModuleResultsAllGroups, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonModuleResultsDistinction, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonModuleResultsFullClass, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonExit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addComponent(jLabel2)))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel4)
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonFullStudentRecord, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonManageStaff, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonModuleResultsByClass, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonUpdateStudentInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonModuleResultsAllGroups, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonModuleResultsDistinction, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonCoursesAndModules, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonModuleResultsFullClass, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonExit, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonBackToLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExitActionPerformed
    this.dispose();       
    }//GEN-LAST:event_jButtonExitActionPerformed

    private void jButtonManageStaffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonManageStaffActionPerformed
    Admin_ManageStaff f = new Admin_ManageStaff();
    f.setVisible(true);
    this.dispose();
    }//GEN-LAST:event_jButtonManageStaffActionPerformed

    private void jButtonBackToLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackToLoginActionPerformed
    Login_Frame f = new Login_Frame();
    f.setVisible(true);
    this.dispose();
    }//GEN-LAST:event_jButtonBackToLoginActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
     
    }//GEN-LAST:event_formWindowActivated

    private void jButtonUpdateStudentInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUpdateStudentInfoActionPerformed
    Admin_ManageStudent f = new Admin_ManageStudent();
    f.setVisible(true);
    this.dispose();    // TODO add your handling code here:
    }//GEN-LAST:event_jButtonUpdateStudentInfoActionPerformed

    private void jButtonFullStudentRecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFullStudentRecordActionPerformed
    FullStudentReport f = new FullStudentReport();
    f.setVisible(true);
    this.dispose();
    }//GEN-LAST:event_jButtonFullStudentRecordActionPerformed

    private void jButtonModuleResultsByClassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModuleResultsByClassActionPerformed
    Reports_ModuleByClass f = new Reports_ModuleByClass();
    f.setVisible(true);
    this.dispose();
    }//GEN-LAST:event_jButtonModuleResultsByClassActionPerformed

    private void jButtonModuleResultsAllGroupsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModuleResultsAllGroupsActionPerformed
    Reports_Module_by_AllGroups f = new Reports_Module_by_AllGroups();
    f.setVisible(true);
    this.dispose();
    }//GEN-LAST:event_jButtonModuleResultsAllGroupsActionPerformed

    private void jButtonModuleResultsDistinctionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModuleResultsDistinctionActionPerformed
    Reports_Distinction_Students_by_Module f = new Reports_Distinction_Students_by_Module();
    f.setVisible(true);
    this.dispose();
    }//GEN-LAST:event_jButtonModuleResultsDistinctionActionPerformed

    private void jButtonModuleResultsFullClassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModuleResultsFullClassActionPerformed
    Reports_Full_Class_Group f = new Reports_Full_Class_Group();
    f.setVisible(true);
    this.dispose();
    }//GEN-LAST:event_jButtonModuleResultsFullClassActionPerformed

    private void jButtonCoursesAndModulesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCoursesAndModulesActionPerformed
    Admin_Options_CoursesAndModules f = new Admin_Options_CoursesAndModules();
    f.setVisible(true);
    this.dispose();
    }//GEN-LAST:event_jButtonCoursesAndModulesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Admin_Options().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBackToLogin;
    private javax.swing.JButton jButtonCoursesAndModules;
    private javax.swing.JButton jButtonExit;
    private javax.swing.JButton jButtonFullStudentRecord;
    private javax.swing.JButton jButtonManageStaff;
    private javax.swing.JButton jButtonModuleResultsAllGroups;
    private javax.swing.JButton jButtonModuleResultsByClass;
    private javax.swing.JButton jButtonModuleResultsDistinction;
    private javax.swing.JButton jButtonModuleResultsFullClass;
    private javax.swing.JButton jButtonUpdateStudentInfo;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu1;
    // End of variables declaration//GEN-END:variables
}
