/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Login_Frames;

import Reports_Frames.FullStudentReport;
import Admin_Frames.Admin_Options;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import java.util.List;
import java.util.ArrayList;

/**
 *
 * @author cjunior
 */
public class SearchStudent_Old extends javax.swing.JFrame {

    private static final String URL = "jdbc:mysql://localhost:3306/final_project";
    private static final String USER = "root";      // seu usuário MySQL
    private static final String PASSWORD = "Root@1234"; // sua senha
    private static int selectedStudentId;

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(SearchStudent_Old.class.getName());

    /**
     * Creates new form StudentFrame
     */
    public SearchStudent_Old() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonSearch = new javax.swing.JButton();
        jButtonExit = new javax.swing.JButton();
        jLabelStudentName = new javax.swing.JLabel();
        jButtonSeeResults = new javax.swing.JButton();
        jLabelStudentName1 = new javax.swing.JLabel();
        jButtonBackToAdmin_Options = new javax.swing.JButton();
        jLabelCourseCode = new javax.swing.JLabel();
        jLabelCourse = new javax.swing.JLabel();
        jButtonClean = new javax.swing.JButton();
        jComboBoxSelectStudent = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jButtonSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Images/Search_icon.png"))); // NOI18N
        jButtonSearch.setText("Search");
        jButtonSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSearchActionPerformed(evt);
            }
        });

        jButtonExit.setText("Exit");
        jButtonExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExitActionPerformed(evt);
            }
        });

        jLabelStudentName.setText("Student name:");
        jLabelStudentName.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jButtonSeeResults.setText("See results");
        jButtonSeeResults.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSeeResultsActionPerformed(evt);
            }
        });

        jLabelStudentName1.setText("Select student:");

        jButtonBackToAdmin_Options.setText("Back to Login");
        jButtonBackToAdmin_Options.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackToAdmin_OptionsActionPerformed(evt);
            }
        });

        jLabelCourseCode.setText("Course code:");
        jLabelCourseCode.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jLabelCourse.setText("Course:");
        jLabelCourse.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jButtonClean.setText("Clean");
        jButtonClean.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCleanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButtonBackToAdmin_Options, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonExit, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(199, 199, 199)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jButtonClean, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 146, Short.MAX_VALUE)
                                    .addComponent(jButtonSeeResults, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jLabelStudentName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabelCourseCode, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabelCourse, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelStudentName1, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jComboBoxSelectStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonSearch)))
                        .addGap(0, 207, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(162, 162, 162)
                .addComponent(jLabelStudentName1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxSelectStudent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(jLabelStudentName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelCourseCode)
                .addGap(2, 2, 2)
                .addComponent(jLabelCourse)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSeeResults, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonClean, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 109, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonExit, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonBackToAdmin_Options, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSearchActionPerformed
        String SelectedStudent = jComboBoxSelectStudent.getSelectedItem().toString();

         if (SelectedStudent == null) {
        JOptionPane.showMessageDialog(this, "Please select a student.");
        return;
    }

    // Pega tudo antes do ":"
    String idPart = SelectedStudent.split(":")[0].trim();
    int studentId;

    try {
        studentId = Integer.parseInt(idPart);
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Invalid student selection.");
        return;
    }

    String sql = """
        SELECT s.class_group_code, s.student_id, s.first_name, s.middle_name, s.surname, c.course_name
        FROM student s
        JOIN class_group cg ON s.class_group_code = cg.class_group_code
        JOIN course c ON cg.course_code = c.course_code
        WHERE s.student_id = ?
    """;

    try (Connection con = DriverManager.getConnection(URL, USER, PASSWORD);
         PreparedStatement ps = con.prepareStatement(sql)) {

        ps.setInt(1, studentId);

        try (ResultSet res = ps.executeQuery()) {
            if (res.next()) {
                String fullName =
                        (res.getString("first_name") + " " +
                         res.getString("middle_name") + " " +
                         res.getString("surname"))
                         .trim().replaceAll("\\s+", " ");

                int courseId = res.getInt("class_group_code");
                String courseName = res.getString("course_name");

                jLabelStudentName.setText("Student name: " + fullName);
                jLabelCourseCode.setText("Course code: " + courseId);
                jLabelCourse.setText("Course: " + courseName);

                selectedStudentId = res.getInt("student_id");

                jLabelStudentName.setVisible(true);
                jLabelCourseCode.setVisible(true);
                jLabelCourse.setVisible(true);

                jButtonSeeResults.setEnabled(true);
                jButtonClean.setEnabled(true);
                jButtonSeeResults.requestFocus();
            } else {
                JOptionPane.showMessageDialog(this, "Student not found.");
            }
        }

    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Erro: " + e.getMessage());
    }
        jLabelStudentName.setVisible(true);
        jLabelCourse.setVisible(true);
        jLabelCourseCode.setVisible(true);
        jButtonSeeResults.setEnabled(true);
        jButtonClean.setEnabled(true);
        jButtonSeeResults.requestFocus(true);
    }//GEN-LAST:event_jButtonSearchActionPerformed

    private void jButtonExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExitActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonExitActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        jLabelStudentName.setVisible(false);
        jLabelCourseCode.setVisible(false);
        jLabelCourse.setVisible(false);
        jButtonClean.setEnabled(false);
        jButtonSeeResults.setEnabled(false);

        jComboBoxSelectStudent.removeAllItems();

        String sql = "SELECT student_id, first_name, middle_name FROM student ORDER BY first_name, middle_name";

        try (Connection con = DriverManager.getConnection(URL, USER, PASSWORD); PreparedStatement ps = con.prepareStatement(sql); ResultSet res = ps.executeQuery()) {

         

            while (res.next()) {
                int id = res.getInt("student_id");
                String first = res.getString("first_name");
                String middle = res.getString("middle_name");

                String name
                        = (first == null ? "" : first) + " "
                        + (middle == null ? "" : middle);

                name = name.trim().replaceAll("\\s+", " ");

                jComboBoxSelectStudent.addItem(id + " : " + name);
            }

            jComboBoxSelectStudent.setSelectedIndex(0);

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Erro: " + e.getMessage());
        }
        jComboBoxSelectStudent.setSelectedIndex(-1);


    }//GEN-LAST:event_formWindowActivated

    private void jButtonBackToAdmin_OptionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackToAdmin_OptionsActionPerformed
        Admin_Options f = new Admin_Options();
        f.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonBackToAdmin_OptionsActionPerformed

    private void jButtonCleanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCleanActionPerformed
        jLabelStudentName.setVisible(false);
        jLabelCourseCode.setVisible(false);
        jLabelCourse.setVisible(false);
        jComboBoxSelectStudent.setSelectedIndex(-1);
        jButtonSeeResults.setEnabled(false);
    }//GEN-LAST:event_jButtonCleanActionPerformed

    private void jButtonSeeResultsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSeeResultsActionPerformed
        FullStudentReport f = new FullStudentReport(selectedStudentId);
        //Ver depois
        f.setLocationRelativeTo(this);
        f.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonSeeResultsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new SearchStudent_Old().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBackToAdmin_Options;
    private javax.swing.JButton jButtonClean;
    private javax.swing.JButton jButtonExit;
    private javax.swing.JButton jButtonSearch;
    private javax.swing.JButton jButtonSeeResults;
    private javax.swing.JComboBox<String> jComboBoxSelectStudent;
    private javax.swing.JLabel jLabelCourse;
    private javax.swing.JLabel jLabelCourseCode;
    private javax.swing.JLabel jLabelStudentName;
    private javax.swing.JLabel jLabelStudentName1;
    // End of variables declaration//GEN-END:variables
}
